import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

// Pins the reusable region SQL (generated by scripts/regions) and the regional
// targeting rules, so a regeneration or hand edit cannot silently drop
// districts, weaken permissions or let the auth trigger block sign-ups.

const regions = readFileSync(new URL("../../../../supabase/migrations/20260919100000_kunthai_country_regions.sql", import.meta.url), "utf8");
const targeting = readFileSync(new URL("../../../../supabase/migrations/20260919110000_regional_targeting.sql", import.meta.url), "utf8");
const territories = readFileSync(new URL("../../../../supabase/migrations/20260920120000_kunthai_territory_regions.sql", import.meta.url), "utf8");
const countrySeed = readFileSync(new URL("../../../../supabase/migrations/20260712190000_global_full_access_country_rollout.sql", import.meta.url), "utf8");

const ROW = /^ {2}\('([A-Z]{2})', '([^']+)', '((?:[^']|'')*)', '((?:[^']|'')*)', '((?:[^']|'')*)', (null|'[^']*'), (\d), /gm;
const rows = [...regions.matchAll(ROW)].map(([, country, code, name, display, type, parent, level]) => ({
  country, code, name, display, type, parent: parent === "null" ? null : parent.slice(1, -1), level: Number(level),
}));

const territoryRows = [...territories.matchAll(ROW)].map(([, country, code, name, display, type, parent, level]) => ({
  country, code, name, display, type, parent: parent === "null" ? null : parent.slice(1, -1), level: Number(level),
}));

// Every country KunThai sells in, from the rollout migration that seeds them.
const SEEDED = /^ {2}\('([A-Z]{2})', '[^']+', '\+/gm;
const seededCountries = [...new Set([...countrySeed.matchAll(SEEDED)].map(([, iso]) => iso))];

function functionBody(source, name) {
  const start = source.search(new RegExp(`create or replace function public\\.${name}\\(`, "i"));
  assert.ok(start >= 0, `${name} is defined`);
  const opening = /\bas\s+(\$[a-z_]*\$)/gi;
  opening.lastIndex = start;
  const match = opening.exec(source);
  assert.ok(match, `${name} has a body`);
  const bodyStart = match.index + match[0].length;
  return source.slice(start, source.indexOf(match[1], bodyStart));
}

test("every subdivision row is well formed and parents exist", () => {
  assert.ok(rows.length > 5000, `expected the full world list, got ${rows.length}`);
  const codes = new Set(rows.map((row) => row.code));
  assert.equal(codes.size, rows.length, "codes are unique");
  for (const row of rows) {
    assert.match(row.code, /^[A-Z]{2}-[A-Z0-9]+$/, row.code);
    assert.ok(row.code.startsWith(`${row.country}-`), row.code);
    if (row.parent) assert.ok(codes.has(row.parent), `${row.code} parent ${row.parent}`);
    assert.equal(row.level === 1, !row.parent, `${row.code} level matches its parent`);
  }
});

test("Sierra Leone has its 16 districts under the five provinces", () => {
  const districts = rows.filter((row) => row.country === "SL" && row.type === "District");
  assert.equal(districts.length, 16);
  assert.deepEqual(
    districts.map((row) => row.display).sort(),
    ["Bo", "Bombali", "Bonthe", "Falaba", "Kailahun", "Kambia", "Karene", "Kenema", "Koinadugu", "Kono", "Moyamba", "Port Loko", "Pujehun", "Tonkolili", "Western Area Rural", "Western Area Urban"],
  );
  assert.equal(rows.find((row) => row.code === "SL-KAMBIA").parent, "SL-NW");
  assert.match(regions, /\('SL', 2, 'District', 'Districts'\)/);
});

test("Nigeria has 36 states plus the FCT, and the USA its 50 states plus DC", () => {
  assert.equal(rows.filter((row) => row.country === "NG").length, 37);
  assert.equal(rows.filter((row) => row.country === "US" && row.type === "State").length, 50);
  assert.ok(rows.some((row) => row.code === "US-DC"));
  assert.match(regions, /\('NG', 1, 'State', 'States'\)/);
});

test("every KunThai country has areas to target, not just the 202 ISO covers", () => {
  const covered = new Set([...rows, ...territoryRows].map((row) => row.country));
  const missing = seededCountries.filter((iso) => !covered.has(iso));
  assert.ok(seededCountries.length > 240, `expected every seeded country, got ${seededCountries.length}`);
  assert.deepEqual(missing, [], `countries with no state, district or area: ${missing.join(", ")}`);
});

test("the territories ISO skips get real areas, and their own labels", () => {
  const codes = new Set(rows.map((row) => row.code));
  assert.equal(new Set(territoryRows.map((row) => row.country)).size, 50);
  for (const row of territoryRows) {
    assert.match(row.code, /^[A-Z]{2}-[A-Z0-9]{4,}$/, `${row.code} cannot collide with an ISO code`);
    assert.ok(!codes.has(row.code), `${row.code} is not already in the world file`);
    assert.equal(row.level, 1, row.code);
    assert.equal(row.parent, null, row.code);
  }
  // The places in the screenshot that could only offer "entire country".
  assert.equal(territoryRows.filter((row) => row.country === "BM").length, 11);
  assert.ok(territoryRows.some((row) => row.code === "BM-SANDYS"));
  assert.equal(territoryRows.filter((row) => row.country === "IM").length, 22);
  assert.equal(territoryRows.filter((row) => row.country === "PR").length, 78);
  assert.match(territories, /\('BM', 1, 'Parish', 'Parishes'\)/);
  assert.match(territories, /\('PR', 1, 'Municipality', 'Municipalities'\)/);
  assert.match(territories, /\('YT', 1, 'Commune', 'Communes'\)/);
});

test("the territory file is safe to run again", () => {
  assert.match(territories, /on conflict \(code\) do update set/);
  assert.match(territories, /select public\.kunthai_refresh_region_paths\(\);/);
  assert.doesNotMatch(territories, /\bdelete from public\.kunthai_country_regions\b/);
  assert.doesNotMatch(territories, /\bdrop (table|function)\b/i);
});

test("the auth trigger can never block a sign-up or profile save", () => {
  const trigger = functionBody(regions, "kunthai_sync_account_region_on_auth_user");
  assert.match(trigger, /exception when others then\s+raise warning/);
  assert.match(regions, /revoke all on function public\.kunthai_sync_account_region\(uuid\) from public, anon, authenticated;/);
  assert.match(regions, /revoke all on function public\.kunthai_account_in_regions\(uuid, uuid\[\]\) from public, anon, authenticated;/);
});

test("the region file is safe to run again", () => {
  assert.match(regions, /create table if not exists public\.kunthai_country_regions/);
  assert.match(regions, /on conflict \(code\) do update set/);
  assert.doesNotMatch(regions, /\bdelete from public\.kunthai_country_regions\b/);
  assert.doesNotMatch(regions, /\bdrop table\b/i);
});

test("regional delivery and admin search are enforced on the server", () => {
  assert.match(functionBody(targeting, "get_recommended_explore_ads"), /kunthai_account_in_regions\(p_user_id, ad\.target_region_ids\)/);
  assert.match(functionBody(targeting, "admin_search_campaign_users"), /admin_has_permission\('notifications\.manage'\)/);
  assert.match(functionBody(targeting, "admin_campaign_region_counts"), /admin_has_permission\('notifications\.manage'\)/);
  assert.match(functionBody(targeting, "admin_validate_campaign_spec"), /One of the chosen states or districts is not valid/);
  assert.match(functionBody(targeting, "admin_notification_user_matches_location"), /place\.region_path && wanted\.region_ids/);
  // Email addresses and phone numbers are never searched or returned.
  assert.doesNotMatch(functionBody(targeting, "admin_search_campaign_users"), /email|phone/i);
  assert.match(targeting, /revoke all on function public\.admin_notification_user_matches_location\(uuid, jsonb\) from public, anon, authenticated;/);
  for (const wrapper of ["create_explore_ad_campaign_in_regions", "create_marketplace_visibility_promotion_in_regions", "create_marketplace_listing_promotion_in_regions"]) {
    assert.match(functionBody(targeting, wrapper), /kunthai_clean_region_ids\(p_target_region_ids, 30\)/, wrapper);
  }
});
