-- ============================================================================
-- KunThai country regions: every state / province / district / county of every
-- country in public.kunthai_countries, stored in the database.
--
-- GENERATED by web/scripts/regions/buildCountryRegionsSql.mjs from the ISO
-- 3166-2 database (Debian iso-codes) plus the curated additions in
-- web/scripts/regions/regionSupplements.mjs (Sierra Leone's 16 districts, Hong
-- Kong and Kosovo districts, English names, town -> district aliases).
-- ISO data used: pycountry 26.2.16 (Debian iso-codes), pycountry/databases/iso3166-2.json.
-- Edit those files and regenerate instead of editing this file by hand.
--
-- REUSABLE: safe to run any number of times (SQL Editor or migration). Rows are
-- upserted by code, parents and paths are recomputed, and nothing is deleted.
-- An administrator can switch a region off with is_active = false; re-running
-- keeps that choice.
--
-- Contents
--   1. Country labels  (kunthai_countries.subdivision_label: "State", "District", ...)
--   2. kunthai_country_regions  (/*@REGION_COUNT@*/ subdivisions, /*@COUNTRY_COUNT@*/ countries, with hierarchy)
--   3. Name matching   (kunthai_region_key, kunthai_resolve_region)
--   4. Where each account is  (kunthai_account_regions, kept in sync from the profile)
--   5. Client RPCs     (kunthai_get_country_regions, kunthai_resolve_region_match, kunthai_get_my_region)
--   6. Targeting helpers used by adverts, UrMall promotions and campaigns
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. Country labels
-- ----------------------------------------------------------------------------
alter table public.kunthai_countries
  add column if not exists subdivision_label text,
  add column if not exists subdivision_label_plural text,
  add column if not exists subdivision_level smallint;

comment on column public.kunthai_countries.subdivision_label is
  'What people in this country call the areas KunThai targets (State, District, County, Region...).';

-- ----------------------------------------------------------------------------
-- 3a. Name keys (defined before the table because its trigger uses them)
-- ----------------------------------------------------------------------------

-- Folds accents, drops punctuation and generic words ("state", "district",
-- "city", "area", "federal capital territory"...), so "Lagos State", "lagos"
-- and "LAGOS" share a key, and "Makeni City" matches "Makeni".
create or replace function public.kunthai_region_plain_key(value text)
returns text
language sql
immutable
parallel safe
set search_path = ''
as $$
  select btrim(regexp_replace(
    lower(translate(coalesce(value, ''), /*@TRANSLATE_FROM@*/, /*@TRANSLATE_TO@*/)),
    '[^a-z0-9]+', ' ', 'g'
  ));
$$;

create or replace function public.kunthai_region_key(value text)
returns text
language sql
immutable
parallel safe
set search_path = ''
as $$
  with plain as (select public.kunthai_region_plain_key(value) as text_value)
  select coalesce(nullif(btrim(regexp_replace(regexp_replace(
      ' ' || text_value || ' ',
      ' (state|states|province|provinces|district|districts|region|regions|county|counties|governorate|prefecture|department|municipality|territory|parish|emirate|division|area|city|of|the|federal|capital|autonomous|metropolitan)(?= )',
      '', 'g'), '\s+', ' ', 'g')), ''), text_value)
  from plain;
$$;

create or replace function public.kunthai_region_keys(p_name text, p_display text, p_aliases text[], p_code text)
returns text[]
language sql
immutable
parallel safe
set search_path = ''
as $$
  select coalesce(array_agg(distinct key) filter (where key <> ''), '{}')
  from (
    select public.kunthai_region_key(candidate) as key
    from unnest(array[p_name, p_display] || coalesce(p_aliases, '{}')) candidate
    union all
    select public.kunthai_region_plain_key(candidate)
    from unnest(array[p_name, p_display] || coalesce(p_aliases, '{}')) candidate
    union all
    -- ISO suffixes ("LA" for NG-LA, "CA" for US-CA) resolve too.
    select lower(split_part(p_code, '-', 2))
    where split_part(p_code, '-', 2) ~ '^[A-Za-z]{2,3}$'
  ) keys;
$$;

-- ----------------------------------------------------------------------------
-- 2. Regions table
-- ----------------------------------------------------------------------------
create table if not exists public.kunthai_country_regions (
  id uuid primary key default gen_random_uuid(),
  country_iso text not null references public.kunthai_countries(iso2) on update cascade on delete cascade,
  code text not null,
  name text not null,
  display_name text not null,
  type_label text not null,
  region_type text not null default 'region',
  parent_code text,
  parent_id uuid references public.kunthai_country_regions(id) on delete set null,
  level smallint not null default 1 check (level between 1 and 4),
  path_ids uuid[] not null default '{}',
  aliases text[] not null default '{}',
  search_keys text[] not null default '{}',
  source text not null default 'iso_3166_2' check (source in ('iso_3166_2', 'kunthai')),
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint kunthai_country_regions_code_key unique (code),
  constraint kunthai_country_regions_code_format check (code ~ '^[A-Z]{2}-[A-Z0-9]+$')
);

comment on table public.kunthai_country_regions is
  'States, provinces, districts, counties... of every KunThai country. path_ids lists the region and its ancestors (root first), so "targets && path_ids" means the region is inside a targeted area.';

create index if not exists kunthai_country_regions_country_idx on public.kunthai_country_regions (country_iso, sort_order);
create index if not exists kunthai_country_regions_parent_idx on public.kunthai_country_regions (parent_id);
create index if not exists kunthai_country_regions_keys_idx on public.kunthai_country_regions using gin (search_keys);
create index if not exists kunthai_country_regions_path_idx on public.kunthai_country_regions using gin (path_ids);

create or replace function public.kunthai_country_regions_prepare()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.code := upper(btrim(new.code));
  new.country_iso := upper(btrim(new.country_iso));
  new.display_name := coalesce(nullif(btrim(new.display_name), ''), new.name);
  new.region_type := coalesce(nullif(regexp_replace(lower(btrim(new.type_label)), '[^a-z0-9]+', '_', 'g'), ''), 'region');
  new.aliases := coalesce(new.aliases, '{}');
  new.search_keys := public.kunthai_region_keys(new.name, new.display_name, new.aliases, new.code);
  new.updated_at := timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists kunthai_country_regions_prepare on public.kunthai_country_regions;
create trigger kunthai_country_regions_prepare
  before insert or update on public.kunthai_country_regions
  for each row execute function public.kunthai_country_regions_prepare();

alter table public.kunthai_country_regions enable row level security;
drop policy if exists "Anyone can read active regions" on public.kunthai_country_regions;
create policy "Anyone can read active regions" on public.kunthai_country_regions
  for select to anon, authenticated using (is_active);
grant select on public.kunthai_country_regions to anon, authenticated;

-- Seed. Countries missing from kunthai_countries are skipped by the join.
insert into public.kunthai_country_regions as region (
  country_iso, code, name, display_name, type_label, parent_code, level, aliases, source, sort_order
)
select v.country_iso, v.code, v.name, v.display_name, v.type_label, v.parent_code, v.level, v.aliases, v.source, v.sort_order
from (values
/*@REGION_VALUES@*/
) as v(country_iso, code, name, display_name, type_label, parent_code, level, aliases, source, sort_order)
join public.kunthai_countries country on country.iso2 = v.country_iso
on conflict (code) do update set
  country_iso = excluded.country_iso,
  name = excluded.name,
  display_name = excluded.display_name,
  type_label = excluded.type_label,
  parent_code = excluded.parent_code,
  level = excluded.level,
  aliases = excluded.aliases,
  source = excluded.source,
  sort_order = excluded.sort_order
where (region.name, region.display_name, region.type_label, region.parent_code, region.level, region.aliases, region.source, region.sort_order)
  is distinct from (excluded.name, excluded.display_name, excluded.type_label, excluded.parent_code, excluded.level, excluded.aliases, excluded.source, excluded.sort_order);

-- Parents and ancestor paths. Call again after adding regions by hand.
create or replace function public.kunthai_refresh_region_paths()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare changed integer;
begin
  update public.kunthai_country_regions child
  set parent_id = parent.id
  from public.kunthai_country_regions parent
  where parent.code = child.parent_code
    and child.parent_id is distinct from parent.id;

  update public.kunthai_country_regions child
  set parent_id = null
  where child.parent_code is null and child.parent_id is not null;

  with recursive paths as (
    select id, array[id] as path, 1 as depth
    from public.kunthai_country_regions
    where parent_id is null
    union all
    select child.id, paths.path || child.id, paths.depth + 1
    from public.kunthai_country_regions child
    join paths on child.parent_id = paths.id
    where paths.depth < 6
  )
  update public.kunthai_country_regions region
  set path_ids = paths.path, level = least(4, array_length(paths.path, 1))
  from paths
  where paths.id = region.id
    and (region.path_ids is distinct from paths.path or region.level <> least(4, array_length(paths.path, 1)));
  get diagnostics changed = row_count;
  return changed;
end;
$$;

revoke all on function public.kunthai_refresh_region_paths() from public, anon, authenticated;
select public.kunthai_refresh_region_paths();

-- Country labels
update public.kunthai_countries country
set subdivision_level = v.level,
    subdivision_label = v.label,
    subdivision_label_plural = v.plural
from (values
/*@LABEL_VALUES@*/
) as v(country_iso, level, label, plural)
where country.iso2 = v.country_iso
  and (country.subdivision_level, country.subdivision_label, country.subdivision_label_plural)
      is distinct from (v.level::smallint, v.label, v.plural);

-- ----------------------------------------------------------------------------
-- 3b. Resolving free text ("Lumley, Freetown", "Lagos State", "Kambia") to a region
-- ----------------------------------------------------------------------------
-- Every comma-separated part is tried; the most specific level wins (a town
-- listed under a district beats the same word on its province).
create or replace function public.kunthai_resolve_region(p_country text, p_text text)
returns uuid
language sql
stable
set search_path = public
as $$
  with target as (
    select public.kunthai_normalize_country_iso(p_country) as iso
  ),
  parts as (
    select public.kunthai_region_key(part) as key, position
    from unnest(array_prepend(coalesce(p_text, ''), regexp_split_to_array(coalesce(p_text, ''), '\s*[,;/|]\s*')))
      with ordinality as candidate(part, position)
  )
  select region.id
  from parts
  cross join target
  join public.kunthai_country_regions region
    on region.country_iso = target.iso
   and region.is_active
   and region.search_keys @> array[parts.key]
  where parts.key <> '' and target.iso <> ''
  order by region.level desc, parts.position, region.sort_order
  limit 1;
$$;

-- Keeps only real, active region ids (deduplicated, at most p_limit).
create or replace function public.kunthai_clean_region_ids(p_region_ids uuid[], p_limit integer default 50)
returns uuid[]
language sql
stable
set search_path = public
as $$
  select coalesce(array_agg(id order by first_position), '{}')
  from (
    select region.id, min(candidate.position) as first_position
    from unnest(coalesce(p_region_ids, '{}')) with ordinality as candidate(region_id, position)
    join public.kunthai_country_regions region on region.id = candidate.region_id and region.is_active
    group by region.id
    order by min(candidate.position)
    limit greatest(1, coalesce(p_limit, 50))
  ) cleaned;
$$;

-- True when p_region_id is one of the targets or lies inside one of them.
create or replace function public.kunthai_region_in_targets(p_region_id uuid, p_targets uuid[])
returns boolean
language sql
stable
set search_path = public
as $$
  select coalesce(p_region_id is not null and exists (
    select 1 from public.kunthai_country_regions region
    where region.id = p_region_id and region.path_ids && coalesce(p_targets, '{}')
  ), false);
$$;

-- ----------------------------------------------------------------------------
-- 4. Where each account is
-- ----------------------------------------------------------------------------
-- One row per account: the state/district chosen in the profile (source
-- 'profile' or 'device'), otherwise one matched from the profile city
-- ('city_match'). Maintained only by the trigger below.
create table if not exists public.kunthai_account_regions (
  user_id uuid primary key references auth.users(id) on delete cascade,
  country_iso text,
  region_id uuid references public.kunthai_country_regions(id) on delete cascade,
  region_path uuid[] not null default '{}',
  source text not null default 'city_match' check (source in ('profile', 'device', 'city_match')),
  matched_text text,
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists kunthai_account_regions_region_idx on public.kunthai_account_regions (region_id);
create index if not exists kunthai_account_regions_path_idx on public.kunthai_account_regions using gin (region_path);

alter table public.kunthai_account_regions enable row level security;
drop policy if exists "People read their own region" on public.kunthai_account_regions;
create policy "People read their own region" on public.kunthai_account_regions
  for select to authenticated using (user_id = auth.uid());
grant select on public.kunthai_account_regions to authenticated;

create or replace function public.kunthai_sync_account_region(p_user_id uuid)
returns uuid
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  meta jsonb;
  anonymous boolean;
  chosen text;
  v_region public.kunthai_country_regions;
  v_source text;
  v_text text;
begin
  select coalesce(users.raw_user_meta_data, '{}'::jsonb), coalesce(users.is_anonymous, false)
    into meta, anonymous
  from auth.users users where users.id = p_user_id;
  if not found or anonymous then
    delete from public.kunthai_account_regions where user_id = p_user_id;
    return null;
  end if;

  chosen := btrim(coalesce(meta->>'region_id', ''));
  if chosen ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' then
    select * into v_region from public.kunthai_country_regions where id = chosen::uuid and is_active;
    if v_region.id is not null then
      v_source := case when meta->>'region_source' = 'device' then 'device' else 'profile' end;
      v_text := v_region.display_name;
    end if;
  end if;

  if v_region.id is null then
    v_text := nullif(concat_ws(', ',
      nullif(btrim(meta->>'city'), ''),
      nullif(btrim(meta->>'region_name'), ''),
      nullif(btrim(meta->>'state'), '')
    ), '');
    if v_text is not null then
      select * into v_region
      from public.kunthai_country_regions
      where id = public.kunthai_resolve_region(
        public.kunthai_resolve_country_iso(coalesce(nullif(meta->>'country_code', ''), nullif(meta->>'country', ''))),
        v_text
      );
      v_source := 'city_match';
    end if;
  end if;

  if v_region.id is null then
    delete from public.kunthai_account_regions where user_id = p_user_id;
    return null;
  end if;

  insert into public.kunthai_account_regions (user_id, country_iso, region_id, region_path, source, matched_text, updated_at)
  values (p_user_id, v_region.country_iso, v_region.id, v_region.path_ids, v_source, left(v_text, 200), timezone('utc', now()))
  on conflict (user_id) do update set
    country_iso = excluded.country_iso,
    region_id = excluded.region_id,
    region_path = excluded.region_path,
    source = excluded.source,
    matched_text = excluded.matched_text,
    updated_at = excluded.updated_at
  where (kunthai_account_regions.region_id, kunthai_account_regions.region_path, kunthai_account_regions.source)
    is distinct from (excluded.region_id, excluded.region_path, excluded.source);

  return v_region.id;
end;
$$;

revoke all on function public.kunthai_sync_account_region(uuid) from public, anon, authenticated;

-- Never blocks sign-up or profile saves: a failure here only logs a warning.
create or replace function public.kunthai_sync_account_region_on_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if tg_op = 'UPDATE'
     and (old.raw_user_meta_data->>'region_id') is not distinct from (new.raw_user_meta_data->>'region_id')
     and (old.raw_user_meta_data->>'region_source') is not distinct from (new.raw_user_meta_data->>'region_source')
     and (old.raw_user_meta_data->>'city') is not distinct from (new.raw_user_meta_data->>'city')
     and (old.raw_user_meta_data->>'country_code') is not distinct from (new.raw_user_meta_data->>'country_code')
     and (old.raw_user_meta_data->>'country') is not distinct from (new.raw_user_meta_data->>'country')
     and old.is_anonymous is not distinct from new.is_anonymous then
    return new;
  end if;
  begin
    perform public.kunthai_sync_account_region(new.id);
  exception when others then
    raise warning 'kunthai_sync_account_region(%) failed: %', new.id, sqlerrm;
  end;
  return new;
end;
$$;

drop trigger if exists kunthai_sync_account_region_on_auth_user on auth.users;
create trigger kunthai_sync_account_region_on_auth_user
  after insert or update on auth.users
  for each row execute function public.kunthai_sync_account_region_on_auth_user();

-- Backfill existing accounts (and repair any drift when re-run).
select count(public.kunthai_sync_account_region(users.id)) from auth.users users;

-- ----------------------------------------------------------------------------
-- 5. Client RPCs
-- ----------------------------------------------------------------------------

-- Everything a picker needs for one country in a single call.
create or replace function public.kunthai_get_country_regions(p_country text)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'countryIso', country.iso2,
    'countryName', country.name,
    'label', coalesce(country.subdivision_label, 'Region'),
    'labelPlural', coalesce(country.subdivision_label_plural, 'Regions'),
    'level', coalesce(country.subdivision_level, 1),
    'regions', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', region.id,
        'code', region.code,
        'name', region.display_name,
        'officialName', region.name,
        'type', region.type_label,
        'parentId', region.parent_id,
        'level', region.level,
        'aliases', region.aliases
      ) order by region.sort_order)
      from public.kunthai_country_regions region
      where region.country_iso = country.iso2 and region.is_active
    ), '[]'::jsonb)
  )
  from public.kunthai_countries country
  where country.iso2 = public.kunthai_normalize_country_iso(p_country);
$$;

-- Match place names (e.g. from device location) to a region of a country.
create or replace function public.kunthai_resolve_region_match(p_country text, p_texts text[])
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object('id', region.id, 'code', region.code, 'name', region.display_name,
    'type', region.type_label, 'parentId', region.parent_id, 'level', region.level, 'countryIso', region.country_iso)
  from public.kunthai_country_regions region
  where region.id = public.kunthai_resolve_region(
    p_country,
    array_to_string(array(select btrim(value) from unnest(coalesce(p_texts, '{}')) value where btrim(coalesce(value, '')) <> ''), ', ')
  );
$$;

-- The signed-in person's region with its ancestors (for "show me what is
-- promoted where I am").
create or replace function public.kunthai_get_my_region()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'regionId', account.region_id,
    'regionPath', to_jsonb(account.region_path),
    'countryIso', account.country_iso,
    'source', account.source,
    'name', region.display_name,
    'type', region.type_label
  )
  from public.kunthai_account_regions account
  join public.kunthai_country_regions region on region.id = account.region_id
  where account.user_id = auth.uid();
$$;

revoke all on function public.kunthai_get_country_regions(text) from public;
revoke all on function public.kunthai_resolve_region_match(text, text[]) from public;
revoke all on function public.kunthai_get_my_region() from public, anon;
grant execute on function public.kunthai_get_country_regions(text) to anon, authenticated;
grant execute on function public.kunthai_resolve_region_match(text, text[]) to anon, authenticated;
grant execute on function public.kunthai_get_my_region() to authenticated;
grant execute on function public.kunthai_region_key(text) to anon, authenticated;
grant execute on function public.kunthai_region_plain_key(text) to anon, authenticated;
grant execute on function public.kunthai_resolve_region(text, text) to authenticated;
grant execute on function public.kunthai_clean_region_ids(uuid[], integer) to authenticated;
grant execute on function public.kunthai_region_in_targets(uuid, uuid[]) to authenticated;

-- ----------------------------------------------------------------------------
-- 6. Targeting helper: is this account inside any of these regions?
-- ----------------------------------------------------------------------------
create or replace function public.kunthai_account_in_regions(p_user_id uuid, p_targets uuid[])
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(cardinality(p_targets), 0) > 0 and exists (
    select 1 from public.kunthai_account_regions account
    where account.user_id = p_user_id and account.region_path && p_targets
  );
$$;

revoke all on function public.kunthai_account_in_regions(uuid, uuid[]) from public, anon, authenticated;
