// Territories and small states that ISO 3166-2 leaves without subdivisions.
//
// ISO lists subdivisions for 202 of the 252 countries KunThai seeds into
// kunthai_countries: overseas territories are ISO subdivisions of their parent
// country (French Guiana is FR-973, Puerto Rico is US-PR), and the smallest
// states and islands have no ISO entries at all. Those 50 places ended up with
// nothing to target, so the campaign, advert and promotion pickers could only
// offer "entire country".
//
// This file gives every one of them the areas people there actually use:
// parishes (Bermuda, Jersey), districts (Anguilla, Cayman Islands), communes
// (Guadeloupe, Mayotte, Reunion), villages (Guam, Niue), municipios (Puerto
// Rico), islands (Cook Islands, Turks and Caicos) or settlements (Ascension,
// Svalbard). Aliases carry the towns and spellings people type.
//
// Used by buildCountryRegionsSql.mjs (the full world file) and by
// buildTerritoryRegionsSql.mjs (the follow-up migration that adds only these).
//
// Shape: { country, type, label, plural, regions: [name, ...aliases][] }
// Codes are generated as <ISO>-<NAME>: at least four characters after the
// dash, so they can never collide with a future official ISO code (three).

export const TERRITORY_REGIONS = [
  {
    country: "AC", type: "Settlement", label: "Settlement", plural: "Settlements",
    regions: [
      ["Georgetown", "George Town"],
      ["Two Boats", "Two Boats Village"],
      ["Traveller's Hill", "Travellers Hill"],
      ["Cat Hill"],
      ["Wideawake Field", "Wideawake Airfield"],
    ],
  },
  {
    country: "AI", type: "District", label: "District", plural: "Districts",
    regions: [
      ["The Valley", "Valley"],
      ["Blowing Point"],
      ["East End"],
      ["George Hill"],
      ["Island Harbour"],
      ["North Hill"],
      ["North Side"],
      ["Sandy Ground"],
      ["Sandy Hill"],
      ["South Hill"],
      ["Stoney Ground"],
      ["The Farrington", "Farrington"],
      ["The Quarter", "Quarter"],
      ["West End"],
    ],
  },
  {
    country: "AQ", type: "Territory", label: "Area", plural: "Areas",
    regions: [
      ["Antarctic Peninsula", "Graham Land", "Palmer Land", "Rothera"],
      ["Ross Dependency", "Ross Sea", "McMurdo", "Scott Base"],
      ["Queen Maud Land", "Dronning Maud Land", "Troll Station"],
      ["Australian Antarctic Territory", "Davis Station", "Mawson Station", "Casey Station"],
      ["Marie Byrd Land"],
      ["Wilkes Land"],
      ["Ellsworth Land"],
      ["South Pole", "Amundsen-Scott"],
    ],
  },
  {
    country: "AS", type: "District", label: "District", plural: "Districts",
    regions: [
      ["Eastern District", "Pago Pago", "Fagatogo", "Utulei", "Aua", "Leloaloa"],
      ["Western District", "Leone", "Tafuna", "Nuuuli", "Pavaiai", "Vailoatai"],
      ["Manu'a District", "Manua", "Ta'u", "Ofu", "Olosega", "Fitiuta"],
      ["Swains Island", "Swains"],
      ["Rose Atoll", "Rose Island"],
    ],
  },
  {
    country: "AW", type: "District", label: "District", plural: "Districts",
    regions: [
      ["Oranjestad West", "Oranjestad"],
      ["Oranjestad East"],
      ["Noord", "Palm Beach", "Malmok", "Tanki Leendert"],
      ["Paradera"],
      ["Santa Cruz"],
      ["Savaneta"],
      ["San Nicolas North", "San Nicolas", "Sint Nicolaas"],
      ["San Nicolas South", "Seroe Colorado"],
    ],
  },
  {
    country: "AX", type: "Municipality", label: "Municipality", plural: "Municipalities",
    regions: [
      ["Mariehamn", "Maarianhamina"],
      ["Brändö", "Brando"],
      ["Eckerö", "Eckero"],
      ["Finström", "Finstrom", "Godby"],
      ["Föglö", "Foglo"],
      ["Geta"],
      ["Hammarland"],
      ["Jomala"],
      ["Kumlinge"],
      ["Kökar", "Kokar"],
      ["Lemland"],
      ["Lumparland"],
      ["Saltvik"],
      ["Sottunga"],
      ["Sund"],
      ["Vårdö", "Vardo"],
    ],
  },
  {
    country: "BL", type: "Quarter", label: "Quarter", plural: "Quarters",
    regions: [
      ["Gustavia"],
      ["Saint-Jean", "St Jean"],
      ["Lorient"],
      ["Flamands", "Anse des Flamands"],
      ["Colombier"],
      ["Corossol"],
      ["Grand Cul-de-Sac"],
      ["Petit Cul-de-Sac"],
      ["Pointe Milou"],
      ["Marigot"],
      ["Vitet"],
      ["Toiny"],
      ["Saline", "Grande Saline"],
      ["Gouverneur", "Anse du Gouverneur"],
      ["Anse des Cayes"],
      ["Public"],
    ],
  },
  {
    country: "BM", type: "Parish", label: "Parish", plural: "Parishes",
    regions: [
      ["Devonshire"],
      ["Hamilton Parish", "Bailey's Bay", "Baileys Bay", "Flatts"],
      ["Paget"],
      ["Pembroke"],
      ["Sandys", "Somerset"],
      ["Smith's", "Smiths"],
      ["Southampton"],
      ["Saint George's", "St George's", "St Georges", "Saint Georges"],
      ["Warwick"],
      ["City of Hamilton", "Hamilton", "Hamilton City"],
      ["Town of St. George", "St George Town", "Town of Saint George"],
    ],
  },
  {
    country: "BV", type: "Area", label: "Area", plural: "Areas",
    regions: [
      ["Bouvet Island", "Bouvetøya", "Bouvetoya"],
      ["Nyrøysa", "Nyroysa"],
      ["Kapp Circoncision", "Cape Circoncision"],
    ],
  },
  {
    country: "CC", type: "Island", label: "Island", plural: "Islands",
    regions: [
      ["West Island"],
      ["Home Island", "Bantam Village"],
      ["South Island"],
      ["Direction Island"],
      ["Horsburgh Island"],
      ["North Keeling", "Pulu Keeling"],
    ],
  },
  {
    country: "CK", type: "Island", label: "Island", plural: "Islands",
    regions: [
      ["Rarotonga", "Avarua", "Arorangi", "Titikaveka", "Matavera", "Nikao"],
      ["Aitutaki", "Arutanga"],
      ["Atiu"],
      ["Mangaia"],
      ["Manihiki"],
      ["Manuae"],
      ["Mauke"],
      ["Mitiaro"],
      ["Nassau"],
      ["Palmerston"],
      ["Penrhyn", "Tongareva"],
      ["Pukapuka"],
      ["Rakahanga"],
      ["Suwarrow", "Suvarov"],
      ["Takutea"],
    ],
  },
  {
    country: "CW", type: "District", label: "District", plural: "Districts",
    regions: [
      ["Willemstad", "Punda", "Otrobanda", "Scharloo", "Pietermaai", "Salina"],
      ["Banda Ariba", "Banda Riba", "Jan Thiel", "Santa Rosa", "Spaanse Water"],
      ["Bandabou", "Banda Bou", "Westpunt", "Barber", "Soto", "Lagun"],
      ["Sint Michiel", "San Michiel", "Piscadera"],
      ["Emmastad", "Julianadorp", "Groot Kwartier"],
    ],
  },
  {
    country: "CX", type: "Settlement", label: "Settlement", plural: "Settlements",
    regions: [
      ["Flying Fish Cove", "The Settlement", "Settlement"],
      ["Silver City"],
      ["Poon Saan"],
      ["Drumsite"],
      ["Waterfall"],
      ["Rocky Point"],
    ],
  },
  {
    country: "EH", type: "Province", label: "Province", plural: "Provinces",
    regions: [
      ["Laâyoune", "Laayoune", "El Aaiún", "El Aaiun"],
      ["Boujdour", "Bojador"],
      ["Es-Semara", "Smara"],
      ["Tarfaya"],
      ["Oued Ed-Dahab", "Dakhla", "Oued Eddahab"],
      ["Aousserd", "Ausserd"],
    ],
  },
  {
    country: "FK", type: "District", label: "Area", plural: "Areas",
    regions: [
      ["Stanley", "Port Stanley"],
      ["East Falkland", "Camp East", "Goose Green", "Darwin"],
      ["West Falkland", "Camp West", "Port Howard", "Fox Bay"],
      ["Mount Pleasant", "Mount Pleasant Complex"],
      ["Outer Islands", "Pebble Island", "Saunders Island", "Sea Lion Island", "Carcass Island"],
    ],
  },
  {
    country: "FO", type: "Region", label: "Region", plural: "Regions",
    regions: [
      ["Streymoy", "Tórshavn", "Torshavn", "Vestmanna"],
      ["Eysturoy", "Runavík", "Runavik", "Fuglafjørður", "Fuglafjordur"],
      ["Vágar", "Vagar", "Sørvágur", "Sorvagur", "Miðvágur"],
      ["Norðoyar", "Nordoyar", "Klaksvík", "Klaksvik", "Viðareiði"],
      ["Sandoy", "Sandur", "Skopun", "Skúvoy"],
      ["Suðuroy", "Suduroy", "Tvøroyri", "Tvoroyri", "Vágur", "Vagur"],
    ],
  },
  {
    country: "GF", type: "Commune", label: "Commune", plural: "Communes",
    regions: [
      ["Cayenne"],
      ["Matoury"],
      ["Rémire-Montjoly", "Remire-Montjoly", "Remire"],
      ["Macouria", "Tonate"],
      ["Montsinéry-Tonnegrande", "Montsinery-Tonnegrande"],
      ["Roura"],
      ["Kourou"],
      ["Sinnamary"],
      ["Iracoubo"],
      ["Saint-Élie", "Saint-Elie"],
      ["Saint-Laurent-du-Maroni", "Saint Laurent du Maroni"],
      ["Mana"],
      ["Awala-Yalimapo"],
      ["Apatou"],
      ["Grand-Santi"],
      ["Papaïchton", "Papaichton"],
      ["Maripasoula"],
      ["Saül", "Saul"],
      ["Régina", "Regina"],
      ["Saint-Georges", "Saint-Georges-de-l'Oyapock"],
      ["Ouanary"],
      ["Camopi"],
    ],
  },
  {
    country: "GG", type: "Parish", label: "Parish", plural: "Parishes",
    regions: [
      ["Saint Peter Port", "St Peter Port", "Town"],
      ["Saint Sampson", "St Sampson", "St Sampson's"],
      ["Vale", "Le Vale"],
      ["Castel", "Le Castel"],
      ["Saint Martin", "St Martin"],
      ["Saint Saviour", "St Saviour"],
      ["Saint Andrew", "St Andrew"],
      ["Saint Pierre du Bois", "St Pierre du Bois"],
      ["Torteval"],
      ["Forest", "La Forêt"],
      ["Alderney", "Saint Anne", "St Anne"],
      ["Sark", "Sercq", "Little Sark"],
      ["Herm"],
    ],
  },
  {
    country: "GI", type: "District", label: "Area", plural: "Areas",
    regions: [
      ["Town Area", "Main Street", "City Centre"],
      ["Upper Town"],
      ["South District", "Europa Point", "Rosia"],
      ["North District", "Glacis", "Laguna Estate"],
      ["Westside", "West Side", "Ocean Village", "Marina Bay"],
      ["Reclamation Areas", "Waterport", "Europort"],
      ["Sandpits", "Alameda"],
      ["East Side", "Catalan Bay", "Sandy Bay"],
    ],
  },
  {
    country: "GP", type: "Commune", label: "Commune", plural: "Communes",
    regions: [
      ["Les Abymes", "Abymes"],
      ["Anse-Bertrand"],
      ["Baie-Mahault"],
      ["Baillif"],
      ["Basse-Terre"],
      ["Bouillante"],
      ["Capesterre-Belle-Eau"],
      ["Capesterre-de-Marie-Galante"],
      ["Deshaies"],
      ["La Désirade", "La Desirade"],
      ["Le Gosier", "Gosier"],
      ["Goyave"],
      ["Gourbeyre"],
      ["Grand-Bourg", "Grand-Bourg de Marie-Galante"],
      ["Lamentin", "Le Lamentin"],
      ["Morne-à-l'Eau", "Morne-a-l'Eau"],
      ["Le Moule", "Moule"],
      ["Petit-Bourg"],
      ["Petit-Canal"],
      ["Pointe-à-Pitre", "Pointe-a-Pitre"],
      ["Pointe-Noire"],
      ["Port-Louis"],
      ["Saint-Claude"],
      ["Saint-François", "Saint-Francois"],
      ["Saint-Louis", "Saint-Louis de Marie-Galante"],
      ["Sainte-Anne"],
      ["Sainte-Rose"],
      ["Terre-de-Bas"],
      ["Terre-de-Haut", "Les Saintes"],
      ["Trois-Rivières", "Trois-Rivieres"],
      ["Vieux-Fort"],
      ["Vieux-Habitants"],
    ],
  },
  {
    country: "GS", type: "Area", label: "Area", plural: "Areas",
    regions: [
      ["King Edward Point"],
      ["Grytviken"],
      ["Bird Island"],
      ["South Georgia"],
      ["South Sandwich Islands", "Southern Thule"],
    ],
  },
  {
    country: "GU", type: "Village", label: "Village", plural: "Villages",
    regions: [
      ["Hagåtña", "Hagatna", "Agana"],
      ["Agana Heights"],
      ["Agat", "Hagat"],
      ["Asan-Maina", "Asan"],
      ["Barrigada"],
      ["Chalan Pago-Ordot", "Ordot", "Chalan Pago"],
      ["Dededo"],
      ["Inarajan", "Inalåhan"],
      ["Mangilao"],
      ["Merizo", "Malesso"],
      ["Mongmong-Toto-Maite", "Mongmong"],
      ["Piti"],
      ["Santa Rita", "Sumai"],
      ["Sinajana"],
      ["Talofofo"],
      ["Tamuning", "Tumon", "Harmon"],
      ["Umatac", "Humåtak"],
      ["Yigo"],
      ["Yona"],
    ],
  },
  {
    country: "HM", type: "Island", label: "Island", plural: "Islands",
    regions: [
      ["Heard Island", "Big Ben", "Atlas Cove"],
      ["McDonald Islands", "McDonald Island"],
      ["Shag Island"],
    ],
  },
  {
    country: "IM", type: "District", label: "Parish or town", plural: "Parishes and towns",
    regions: [
      ["Douglas", "Doolish"],
      ["Onchan"],
      ["Ramsey"],
      ["Peel"],
      ["Castletown"],
      ["Port Erin"],
      ["Port St Mary", "Port Saint Mary"],
      ["Braddan", "Union Mills"],
      ["Marown", "Crosby"],
      ["Santon"],
      ["Malew", "Ballasalla"],
      ["Arbory", "Ballabeg", "Colby"],
      ["Rushen", "Cregneash"],
      ["Patrick", "Glen Maye", "Foxdale"],
      ["German", "St John's", "St Johns"],
      ["Michael", "Kirk Michael"],
      ["Ballaugh"],
      ["Jurby"],
      ["Andreas"],
      ["Bride"],
      ["Lezayre", "Sulby"],
      ["Garff", "Laxey", "Lonan", "Maughold"],
    ],
  },
  {
    country: "IO", type: "Island", label: "Island", plural: "Islands",
    regions: [
      ["Diego Garcia"],
      ["Peros Banhos"],
      ["Salomon Islands"],
      ["Egmont Islands", "Six Islands"],
      ["Great Chagos Bank", "Eagle Islands", "Danger Island"],
    ],
  },
  {
    country: "JE", type: "Parish", label: "Parish", plural: "Parishes",
    regions: [
      ["Saint Helier", "St Helier", "Town"],
      ["Saint Brelade", "St Brelade", "St Aubin"],
      ["Saint Clement", "St Clement"],
      ["Grouville", "Gorey"],
      ["Saint John", "St John"],
      ["Saint Lawrence", "St Lawrence"],
      ["Saint Martin", "St Martin"],
      ["Saint Mary", "St Mary"],
      ["Saint Ouen", "St Ouen"],
      ["Saint Peter", "St Peter"],
      ["Saint Saviour", "St Saviour"],
      ["Trinity"],
    ],
  },
  {
    country: "KY", type: "District", label: "District", plural: "Districts",
    regions: [
      ["George Town", "Georgetown"],
      ["West Bay"],
      ["Bodden Town"],
      ["North Side"],
      ["East End"],
      ["Cayman Brac", "The Brac"],
      ["Little Cayman"],
    ],
  },
  {
    country: "MF", type: "Quarter", label: "Quarter", plural: "Quarters",
    regions: [
      ["Marigot"],
      ["Grand-Case", "Grand Case"],
      ["Quartier d'Orléans", "French Quarter", "Orleans"],
      ["Colombier"],
      ["Cul-de-Sac"],
      ["Anse Marcel"],
      ["Baie Nettlé", "Baie Nettle", "Nettle Bay"],
      ["Terres Basses", "Lowlands"],
      ["Sandy Ground"],
      ["Concordia"],
      ["Oyster Pond"],
      ["Rambaud"],
      ["Friar's Bay", "Friars Bay"],
      ["Mont Vernon", "Orient Bay", "Baie Orientale"],
      ["La Savane"],
    ],
  },
  {
    country: "MO", type: "Parish", label: "Parish", plural: "Parishes",
    regions: [
      ["Nossa Senhora de Fátima", "Nossa Senhora de Fatima", "Our Lady of Fatima", "Areia Preta"],
      ["Santo António", "Santo Antonio", "St Anthony"],
      ["São Lázaro", "Sao Lazaro", "St Lazarus"],
      ["Sé", "Se", "Cathedral", "Macau Peninsula", "Macao Peninsula"],
      ["São Lourenço", "Sao Lourenco", "St Lawrence"],
      ["Nossa Senhora do Carmo", "Taipa", "Our Lady of Carmel"],
      ["São Francisco Xavier", "Coloane", "St Francis Xavier"],
      ["Cotai", "Cotai Strip"],
    ],
  },
  {
    country: "MP", type: "Municipality", label: "Municipality", plural: "Municipalities",
    regions: [
      ["Saipan", "Garapan", "Susupe", "Chalan Kanoa", "Capitol Hill"],
      ["Tinian", "San Jose", "Aguiguan"],
      ["Rota", "Songsong", "Sinapalo"],
      ["Northern Islands", "Pagan", "Agrihan", "Alamagan", "Anatahan"],
    ],
  },
  {
    country: "MQ", type: "Commune", label: "Commune", plural: "Communes",
    regions: [
      ["Fort-de-France"],
      ["Le Lamentin", "Lamentin"],
      ["Schoelcher", "Schœlcher"],
      ["Sainte-Marie"],
      ["Le Robert", "Robert"],
      ["Le François", "Le Francois"],
      ["Ducos"],
      ["Saint-Joseph"],
      ["La Trinité", "La Trinite"],
      ["Rivière-Pilote", "Riviere-Pilote"],
      ["Le Marin", "Marin"],
      ["Sainte-Luce"],
      ["Saint-Esprit"],
      ["Le Diamant", "Diamant"],
      ["Les Trois-Îlets", "Les Trois-Ilets", "Trois-Ilets"],
      ["Rivière-Salée", "Riviere-Salee"],
      ["Saint-Pierre"],
      ["Le Carbet", "Carbet"],
      ["Le Morne-Rouge", "Morne-Rouge"],
      ["Le Morne-Vert", "Morne-Vert"],
      ["Gros-Morne"],
      ["Le Lorrain", "Lorrain"],
      ["Basse-Pointe"],
      ["Macouba"],
      ["Grand'Rivière", "Grand-Riviere", "Grand Riviere"],
      ["L'Ajoupa-Bouillon", "Ajoupa-Bouillon"],
      ["Le Prêcheur", "Le Precheur"],
      ["Fonds-Saint-Denis"],
      ["Bellefontaine"],
      ["Case-Pilote"],
      ["Le Marigot", "Marigot"],
      ["Sainte-Anne"],
      ["Les Anses-d'Arlet", "Anses-d'Arlet"],
      ["Le Vauclin", "Vauclin"],
    ],
  },
  {
    country: "MS", type: "Parish", label: "Parish", plural: "Parishes",
    regions: [
      ["Saint Anthony", "St Anthony", "Plymouth"],
      ["Saint Georges", "St Georges", "Saint George"],
      ["Saint Peter", "St Peter", "Brades", "Little Bay", "Salem", "Davy Hill"],
    ],
  },
  {
    country: "NC", type: "Province", label: "Province", plural: "Provinces",
    regions: [
      ["South Province", "Province Sud", "Nouméa", "Noumea", "Mont-Dore", "Dumbéa", "Dumbea", "Païta", "Paita", "Bourail", "La Foa", "Thio"],
      ["North Province", "Province Nord", "Koné", "Kone", "Koumac", "Poindimié", "Poindimie", "Hienghène", "Touho", "Canala", "Voh"],
      ["Loyalty Islands", "Îles Loyauté", "Iles Loyaute", "Lifou", "Maré", "Mare", "Ouvéa", "Ouvea", "Tiga"],
    ],
  },
  {
    country: "NF", type: "Area", label: "Area", plural: "Areas",
    regions: [
      ["Burnt Pine"],
      ["Kingston"],
      ["Anson Bay"],
      ["Cascade"],
      ["Middlegate"],
      ["Steeles Point"],
      ["Rocky Point"],
      ["Longridge"],
      ["Ball Bay"],
    ],
  },
  {
    country: "NU", type: "Village", label: "Village", plural: "Villages",
    regions: [
      ["Alofi North", "Alofi"],
      ["Alofi South"],
      ["Avatele"],
      ["Hakupu"],
      ["Hikutavake"],
      ["Lakepa"],
      ["Liku"],
      ["Makefu"],
      ["Mutalau"],
      ["Namukulu"],
      ["Tamakautoga"],
      ["Toi"],
      ["Tuapa"],
      ["Vaiea"],
    ],
  },
  {
    country: "PF", type: "Division", label: "Division", plural: "Divisions",
    regions: [
      ["Windward Islands", "Îles du Vent", "Iles du Vent", "Tahiti", "Papeete", "Faaa", "Punaauia", "Pirae", "Mahina", "Moorea", "Paea", "Arue"],
      ["Leeward Islands", "Îles Sous-le-Vent", "Iles Sous-le-Vent", "Bora-Bora", "Bora Bora", "Raiatea", "Uturoa", "Huahine", "Maupiti"],
      ["Marquesas Islands", "Îles Marquises", "Iles Marquises", "Nuku Hiva", "Hiva Oa", "Taiohae", "Ua Pou"],
      ["Austral Islands", "Îles Australes", "Iles Australes", "Tubuai", "Rurutu", "Raivavae", "Rimatara"],
      ["Tuamotu-Gambier", "Tuamotu", "Gambier", "Rangiroa", "Fakarava", "Rikitea", "Hao", "Tikehau"],
    ],
  },
  {
    country: "PM", type: "Commune", label: "Commune", plural: "Communes",
    regions: [
      ["Saint-Pierre", "Saint Pierre"],
      ["Miquelon", "Miquelon-Langlade"],
      ["Langlade", "Grande Miquelon"],
    ],
  },
  {
    country: "PN", type: "Island", label: "Island", plural: "Islands",
    regions: [
      ["Adamstown"],
      ["Pitcairn Island", "Pitcairn"],
      ["Henderson Island", "Henderson"],
      ["Ducie Island", "Ducie"],
      ["Oeno Island", "Oeno"],
    ],
  },
  {
    country: "PR", type: "Municipality", label: "Municipality", plural: "Municipalities",
    regions: [
      ["San Juan", "Santurce", "Río Piedras", "Rio Piedras", "Condado", "Hato Rey"],
      ["Adjuntas"],
      ["Aguada"],
      ["Aguadilla"],
      ["Aguas Buenas"],
      ["Aibonito"],
      ["Añasco", "Anasco"],
      ["Arecibo"],
      ["Arroyo"],
      ["Barceloneta"],
      ["Barranquitas"],
      ["Bayamón", "Bayamon"],
      ["Cabo Rojo"],
      ["Caguas"],
      ["Camuy"],
      ["Canóvanas", "Canovanas"],
      ["Carolina", "Isla Verde"],
      ["Cataño", "Catano"],
      ["Cayey"],
      ["Ceiba"],
      ["Ciales"],
      ["Cidra"],
      ["Coamo"],
      ["Comerío", "Comerio"],
      ["Corozal"],
      ["Culebra"],
      ["Dorado"],
      ["Fajardo"],
      ["Florida"],
      ["Guánica", "Guanica"],
      ["Guayama"],
      ["Guayanilla"],
      ["Guaynabo"],
      ["Gurabo"],
      ["Hatillo"],
      ["Hormigueros"],
      ["Humacao"],
      ["Isabela"],
      ["Jayuya"],
      ["Juana Díaz", "Juana Diaz"],
      ["Juncos"],
      ["Lajas"],
      ["Lares"],
      ["Las Marías", "Las Marias"],
      ["Las Piedras"],
      ["Loíza", "Loiza"],
      ["Luquillo"],
      ["Manatí", "Manati"],
      ["Maricao"],
      ["Maunabo"],
      ["Mayagüez", "Mayaguez"],
      ["Moca"],
      ["Morovis"],
      ["Naguabo"],
      ["Naranjito"],
      ["Orocovis"],
      ["Patillas"],
      ["Peñuelas", "Penuelas"],
      ["Ponce"],
      ["Quebradillas"],
      ["Rincón", "Rincon"],
      ["Río Grande", "Rio Grande"],
      ["Sabana Grande"],
      ["Salinas"],
      ["San Germán", "San German"],
      ["San Lorenzo"],
      ["San Sebastián", "San Sebastian"],
      ["Santa Isabel"],
      ["Toa Alta"],
      ["Toa Baja", "Levittown"],
      ["Trujillo Alto"],
      ["Utuado"],
      ["Vega Alta"],
      ["Vega Baja"],
      ["Vieques"],
      ["Villalba"],
      ["Yabucoa"],
      ["Yauco"],
    ],
  },
  {
    country: "RE", type: "Commune", label: "Commune", plural: "Communes",
    regions: [
      ["Saint-Denis"],
      ["Saint-Paul", "Saint-Gilles"],
      ["Saint-Pierre"],
      ["Le Tampon", "Tampon"],
      ["Saint-André", "Saint-Andre"],
      ["Saint-Louis"],
      ["Le Port", "Port"],
      ["Saint-Joseph"],
      ["Saint-Benoît", "Saint-Benoit"],
      ["Sainte-Marie"],
      ["La Possession"],
      ["Sainte-Suzanne"],
      ["Saint-Leu"],
      ["Bras-Panon"],
      ["L'Étang-Salé", "L'Etang-Sale", "Etang-Sale"],
      ["Saint-Philippe"],
      ["Petite-Île", "Petite-Ile"],
      ["Sainte-Rose"],
      ["Les Avirons", "Avirons"],
      ["Cilaos"],
      ["Entre-Deux"],
      ["La Plaine-des-Palmistes", "Plaine-des-Palmistes"],
      ["Salazie", "Hell-Bourg"],
      ["Les Trois-Bassins", "Trois-Bassins"],
    ],
  },
  {
    country: "SJ", type: "Settlement", label: "Settlement", plural: "Settlements",
    regions: [
      ["Longyearbyen"],
      ["Barentsburg"],
      ["Ny-Ålesund", "Ny-Alesund"],
      ["Sveagruva", "Svea"],
      ["Pyramiden"],
      ["Hornsund"],
      ["Jan Mayen", "Olonkinbyen"],
      ["Bjørnøya", "Bjornoya", "Bear Island"],
      ["Hopen"],
    ],
  },
  {
    country: "SX", type: "District", label: "District", plural: "Districts",
    regions: [
      ["Philipsburg"],
      ["Lower Prince's Quarter", "Lower Princes Quarter"],
      ["Upper Prince's Quarter", "Upper Princes Quarter"],
      ["Cul de Sac"],
      ["Cole Bay"],
      ["Simpson Bay"],
      ["Little Bay", "Cay Bay", "Cay Hill"],
      ["Lowlands", "Maho", "Cupecoy", "Mullet Bay"],
      ["Dutch Quarter"],
      ["Saint Peters", "St Peters"],
      ["Pointe Blanche"],
      ["Oyster Pond"],
    ],
  },
  {
    country: "TA", type: "Settlement", label: "Settlement", plural: "Settlements",
    regions: [
      ["Edinburgh of the Seven Seas", "Edinburgh", "The Settlement"],
      ["Tristan da Cunha"],
      ["Nightingale Islands", "Nightingale Island"],
      ["Inaccessible Island"],
      ["Gough Island"],
    ],
  },
  {
    country: "TC", type: "District", label: "District", plural: "Districts",
    regions: [
      ["Providenciales", "Provo", "Grace Bay", "Blue Hills"],
      ["Grand Turk", "Cockburn Town"],
      ["North Caicos", "Bottle Creek", "Kew"],
      ["Middle Caicos", "Conch Bar"],
      ["South Caicos", "Cockburn Harbour"],
      ["Salt Cay", "Balfour Town"],
      ["West Caicos"],
    ],
  },
  {
    country: "TF", type: "District", label: "District", plural: "Districts",
    regions: [
      ["Kerguelen Islands", "Kerguelen", "Port-aux-Français"],
      ["Crozet Islands", "Crozet", "Alfred Faure"],
      ["Saint Paul and Amsterdam Islands", "Amsterdam Island", "Saint Paul Island"],
      ["Adélie Land", "Adelie Land", "Terre Adélie", "Dumont d'Urville"],
      ["Scattered Islands", "Îles Éparses", "Iles Eparses", "Europa", "Juan de Nova", "Tromelin"],
    ],
  },
  {
    country: "TK", type: "Atoll", label: "Atoll", plural: "Atolls",
    regions: [
      ["Atafu"],
      ["Fakaofo", "Fale"],
      ["Nukunonu"],
    ],
  },
  {
    country: "VA", type: "Area", label: "Area", plural: "Areas",
    regions: [
      ["Vatican City", "Città del Vaticano", "Citta del Vaticano", "Holy See"],
      ["Saint Peter's Square", "St Peter's Square", "Piazza San Pietro"],
      ["Saint Peter's Basilica", "St Peter's Basilica", "Basilica di San Pietro"],
      ["Apostolic Palace", "Palazzo Apostolico"],
      ["Vatican Gardens", "Giardini Vaticani"],
      ["Vatican Museums", "Musei Vaticani"],
    ],
  },
  {
    country: "VG", type: "Island", label: "Island", plural: "Islands",
    regions: [
      ["Tortola", "Road Town", "Cane Garden Bay"],
      ["Virgin Gorda", "Spanish Town", "The Valley"],
      ["Anegada", "The Settlement"],
      ["Jost Van Dyke", "Great Harbour"],
      ["Beef Island"],
      ["Peter Island"],
      ["Cooper Island"],
    ],
  },
  {
    country: "VI", type: "District", label: "District", plural: "Districts",
    regions: [
      ["Saint Thomas", "St Thomas", "Charlotte Amalie", "Red Hook"],
      ["Saint Croix", "St Croix", "Christiansted", "Frederiksted"],
      ["Saint John", "St John", "Cruz Bay", "Coral Bay"],
      ["Water Island"],
    ],
  },
  {
    country: "YT", type: "Commune", label: "Commune", plural: "Communes",
    regions: [
      ["Mamoudzou", "Kaweni", "Passamainty"],
      ["Koungou", "Majicavo"],
      ["Dzaoudzi", "Labattoir"],
      ["Pamandzi"],
      ["Dembéni", "Dembeni"],
      ["Bandraboua"],
      ["Tsingoni", "Combani"],
      ["Sada"],
      ["Bouéni", "Boueni"],
      ["Chiconi"],
      ["Ouangani"],
      ["Bandrélé", "Bandrele"],
      ["Chirongui"],
      ["Kani-Kéli", "Kani-Keli"],
      ["M'Tsangamouji", "Mtsangamouji"],
      ["Acoua"],
      ["Mtsamboro", "M'Tsamboro"],
    ],
  },
];

/** Strip accents and punctuation for the generated code suffix. */
function codeSuffix(name) {
  return name
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, "");
}

/** Rows in the shape buildCountryRegionsSql.mjs uses for EXTRA_REGIONS. */
export function territoryRegionRows() {
  const rows = [];
  const seen = new Set();
  for (const territory of TERRITORY_REGIONS) {
    if (!territory.regions.length) throw new Error(`${territory.country} has no regions`);
    for (const [name, ...aliases] of territory.regions) {
      // Short names ("Sé", "Toi") get the area type appended, so no generated
      // code can ever be three characters and collide with an ISO suffix.
      let suffix = codeSuffix(name);
      if (suffix.length < 4) suffix += codeSuffix(territory.type);
      if (suffix.length < 4) throw new Error(`Code ${territory.country}-${suffix} is too short to be collision-proof`);
      const code = `${territory.country}-${suffix}`;
      if (seen.has(code)) throw new Error(`Duplicate territory code ${code}`);
      seen.add(code);
      rows.push({ code, name, type: territory.type, aliases, parent: null });
    }
  }
  return rows;
}

/** Country label rows: what each territory calls the areas KunThai targets. */
export function territoryLabelRows() {
  return TERRITORY_REGIONS.map((territory) => ({
    country: territory.country,
    level: 1,
    label: territory.label,
    plural: territory.plural,
  }));
}
