-- ============================================================================
-- KunThai territory regions: the areas of the /*@COUNTRY_COUNT@*/ countries and
-- territories ISO 3166-2 leaves without subdivisions.
--
-- GENERATED by web/scripts/regions/buildTerritoryRegionsSql.mjs from
-- web/scripts/regions/territoryRegions.mjs. Edit that file and regenerate
-- instead of editing this one by hand.
--
-- Why: 20260919100000_kunthai_country_regions.sql seeds ISO 3166-2, which
-- covers 202 of the 252 countries in kunthai_countries. Overseas territories
-- are ISO subdivisions of their parent country (French Guiana is FR-973,
-- Puerto Rico is US-PR) and the smallest islands have no ISO entries at all,
-- so Bermuda, the Isle of Man, Puerto Rico, Mayotte, Guam and 45 others had
-- nothing to target: every picker could only offer "entire country". This adds
-- /*@REGION_COUNT@*/ parishes, districts, communes, villages, municipios,
-- islands and settlements so EVERY KunThai country has areas to choose from.
--
-- REUSABLE: safe to run any number of times. Rows are upserted by code, paths
-- are recomputed, and nothing is deleted. An administrator can switch an area
-- off with is_active = false; re-running keeps that choice.
-- ============================================================================

-- Areas. Countries missing from kunthai_countries are skipped by the join.
insert into public.kunthai_country_regions as region (
  country_iso, code, name, display_name, type_label, parent_code, level, aliases, source, sort_order
)
select v.country_iso, v.code, v.name, v.display_name, v.type_label, v.parent_code, v.level, v.aliases, v.source, v.sort_order
from (values
/*@REGION_VALUES@*/
) as v(country_iso, code, name, display_name, type_label, parent_code, level, aliases, source, sort_order)
join public.kunthai_countries country on country.iso2 = v.country_iso
on conflict (code) do update set
  country_iso = excluded.country_iso,
  name = excluded.name,
  display_name = excluded.display_name,
  type_label = excluded.type_label,
  parent_code = excluded.parent_code,
  level = excluded.level,
  aliases = excluded.aliases,
  source = excluded.source,
  sort_order = excluded.sort_order
where (region.name, region.display_name, region.type_label, region.parent_code, region.level, region.aliases, region.source, region.sort_order)
  is distinct from (excluded.name, excluded.display_name, excluded.type_label, excluded.parent_code, excluded.level, excluded.aliases, excluded.source, excluded.sort_order);

-- Parents and ancestor paths (these areas are all top level, but the refresh
-- keeps path_ids filled in for the new rows).
select public.kunthai_refresh_region_paths();

-- What each territory calls its areas ("Parish", "Commune", "Village"…).
update public.kunthai_countries country
set subdivision_level = v.level,
    subdivision_label = v.label,
    subdivision_label_plural = v.plural
from (values
/*@LABEL_VALUES@*/
) as v(country_iso, level, label, plural)
where country.iso2 = v.country_iso
  and (country.subdivision_level, country.subdivision_label, country.subdivision_label_plural)
      is distinct from (v.level::smallint, v.label, v.plural);

-- Place existing accounts in these countries: their profile city is matched
-- against the new areas. kunthai_sync_account_region only reads the profile.
select count(public.kunthai_sync_account_region(users.id))
from auth.users users
where upper(btrim(coalesce(users.raw_user_meta_data->>'country_code', ''))) in (/*@COUNTRY_LIST@*/);
