import { Building2, Check, ChevronDown, Hotel, House, Plus, Store, UtensilsCrossed, X } from "lucide-react";
import { useState } from "react";

import AppPortal from "../../../../shared/AppPortal";
import useBodyScrollLock from "../../../../shared/useBodyScrollLock";

const ICONS = { retail: Store, restaurant: UtensilsCrossed, hotel: Hotel, property_agent: House };
const labelBusinessKind = (kind = "retail") => kind === "property_agent" ? "Real Estate Agent" : kind.replaceAll("_", " ");

export default function BusinessSwitcher({ activeBusinessId, businesses = [], onAddBusiness, onSwitch }) {
  const [open, setOpen] = useState(false);
  useBodyScrollLock(open);
  if (businesses.length < 2) return null;

  return <><button type="button" onClick={() => setOpen(true)} className="relative flex h-10 items-center gap-1 rounded-xl border border-emerald-200 bg-emerald-50 px-2.5 text-emerald-700" aria-label="Switch business"><Building2 size={19} /><ChevronDown size={14} /><span className="absolute -right-1.5 -top-1.5 grid h-5 min-w-5 place-items-center rounded-full bg-emerald-700 px-1 text-[10px] font-black text-white">{businesses.length}</span></button>{open ? <AppPortal><div className="fixed inset-0 z-[1400] flex items-end bg-slate-950/30 p-3 backdrop-blur-sm sm:items-center sm:justify-center" onClick={() => setOpen(false)}><section className="w-full max-w-lg rounded-[28px] bg-white p-5 shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="flex items-start justify-between"><div><p className="text-xs font-black uppercase tracking-wide text-emerald-700">Business workspaces</p><h2 className="mt-1 text-2xl font-black text-gray-950">Choose a business</h2></div><button type="button" onClick={() => setOpen(false)} className="grid h-10 w-10 place-items-center rounded-full bg-gray-100"><X size={18} /></button></div><div className="mt-5 max-h-[55dvh] space-y-2 overflow-y-auto">{businesses.map((business) => { const Icon = ICONS[business.businessKind] || Store; const active = business.id === activeBusinessId; return <button key={business.id} type="button" onClick={() => { onSwitch(business.id); setOpen(false); }} className={`flex w-full items-center gap-3 rounded-2xl border p-3 text-left ${active ? "border-emerald-500 bg-emerald-50" : "border-gray-200"}`}><span className="grid h-11 w-11 place-items-center overflow-hidden rounded-xl bg-gray-100 text-gray-600">{business.identity.logoUrl ? <img src={business.identity.logoUrl} alt="" className="h-full w-full object-cover" /> : <Icon size={20} />}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-black text-gray-950">{business.identity.businessName}</span><span className="mt-0.5 block text-xs font-bold capitalize text-gray-500">{labelBusinessKind(business.businessKind)} · {business.verificationStatus || "pending"}</span></span>{active ? <Check className="text-emerald-700" size={20} /> : null}</button>; })}</div><button type="button" onClick={() => { setOpen(false); onAddBusiness(); }} className="mt-4 flex h-12 w-full items-center justify-center gap-2 rounded-2xl bg-gray-950 text-sm font-black text-white"><Plus size={18} /> Add another business</button></section></div></AppPortal> : null}</>;
}
