// Generates src/data/timezoneCountries.js: IANA time zone → ISO country.
//
//   node scripts/buildTimezoneCountries.mjs [zoneinfoDir]
//
// Source: the tz database's zone.tab (one country per zone) plus the "L"
// link lines of tzdata.zi, so legacy names browsers still report
// ("Asia/Calcutta", "Europe/Kiev") resolve too. zone.tab always wins over a
// link. Default zoneinfo dir is Git for Windows' copy (/mingw64/share/zoneinfo);
// on Linux/macOS pass /usr/share/zoneinfo.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const candidates = [process.argv[2], "/mingw64/share/zoneinfo", "C:/Program Files/Git/mingw64/share/zoneinfo", "/usr/share/zoneinfo"].filter(Boolean);
const zoneDir = candidates.find((dir) => fs.existsSync(path.join(dir, "zone.tab")));
if (!zoneDir) throw new Error("zone.tab not found; pass the zoneinfo directory as the first argument");

const zones = new Map();
// zone.tab lists each country's most populous zone first (New_York for US),
// so the first zone seen per country is its primary one.
const primaryZones = new Map();
for (const line of fs.readFileSync(path.join(zoneDir, "zone.tab"), "utf8").split(/\r?\n/)) {
  if (!line || line.startsWith("#")) continue;
  const [codes, , zone] = line.split("\t");
  if (!codes || !zone) continue;
  const iso = codes.split(",")[0];
  zones.set(zone, iso);
  if (!primaryZones.has(iso)) primaryZones.set(iso, zone);
}

const tzdata = path.join(zoneDir, "tzdata.zi");
let links = 0;
if (fs.existsSync(tzdata)) {
  for (const line of fs.readFileSync(tzdata, "utf8").split(/\r?\n/)) {
    if (!line.startsWith("L ")) continue;
    const [, target, alias] = line.split(" ");
    if (alias && !zones.has(alias) && zones.has(target)) {
      zones.set(alias, zones.get(target));
      links += 1;
    }
  }
}

// zone.tab is ordered geographically, not by population, for a few large
// countries; pin their primary zone to where most people live.
const PRIMARY_ZONE_OVERRIDES = {
  AU: "Australia/Sydney",
  BR: "America/Sao_Paulo",
  CA: "America/Toronto",
  PS: "Asia/Hebron",
  RU: "Europe/Moscow",
  UA: "Europe/Kyiv",
  UZ: "Asia/Tashkent",
  FM: "Pacific/Pohnpei",
};
for (const [iso, zone] of Object.entries(PRIMARY_ZONE_OVERRIDES)) {
  if (zones.get(zone) !== iso) throw new Error(`override ${zone} is not a ${iso} zone`);
  primaryZones.set(iso, zone);
}

const sorted = [...zones.entries()].sort(([a], [b]) => a.localeCompare(b));
const primaryBody = [...primaryZones.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([iso, zone]) => `  ${iso}: ${JSON.stringify(zone)},`).join("\n");
const body = sorted.map(([zone, iso]) => `  ${JSON.stringify(zone)}: ${JSON.stringify(iso)},`).join("\n");
const output = `// GENERATED by scripts/buildTimezoneCountries.mjs from the IANA tz database
// (zone.tab + tzdata.zi links). Do not edit by hand — regenerate.
// ${sorted.length} zones (${links} legacy aliases).

export const TIMEZONE_COUNTRIES = Object.freeze({
${body}
});

// Each country's primary (most populous) zone, for "what day is it there".
export const COUNTRY_PRIMARY_TIMEZONES = Object.freeze({
${primaryBody}
});
`;
fs.writeFileSync(path.join(root, "src/data/timezoneCountries.js"), output);
console.log(`wrote src/data/timezoneCountries.js (${sorted.length} zones, ${links} aliases) from ${zoneDir}`);
