-- KunThai Explore advertising v1
-- Campaign delivery is deliberately isolated from Marketplace, Transport,
-- KunThai Money, and other product surfaces. The Explore post is retained as
-- the native creative/engagement shell so existing likes, comments, saves,
-- moderation, media review, and profile rendering remain compatible.

create table if not exists public.explore_ad_campaigns (
  id uuid primary key default gen_random_uuid(),
  creative_post_id uuid not null unique references public.explore_posts(id) on delete cascade,
  advertiser_id uuid not null references auth.users(id) on delete cascade,
  placement text not null default 'urfeed'
    check (placement in ('urfeed', 'swip', 'both')),
  objective text not null default 'brand_awareness'
    check (objective in (
      'brand_awareness', 'profile_visits', 'followers', 'website_clicks',
      'messages', 'video_views', 'event_promotion'
    )),
  audience_type text not null default 'recommended'
    check (audience_type in ('everyone', 'followers', 'followers_similar', 'recommended', 'nearby')),
  minimum_age integer not null default 13 check (minimum_age between 13 and 120),
  maximum_age integer check (maximum_age between 13 and 120 and maximum_age >= minimum_age),
  gender_target text not null default 'all' check (gender_target in ('all', 'male', 'female')),
  interest_categories text[] not null default '{}',
  target_area text,
  duration_days integer check (duration_days between 1 and 365),
  starts_at timestamptz not null default timezone('utc', now()),
  ends_at timestamptz not null,
  budget_type text not null default 'total' check (budget_type in ('daily', 'total')),
  budget_amount numeric(12, 2) not null default 0 check (budget_amount >= 0),
  currency text not null default 'SLE' check (char_length(currency) between 3 and 5),
  status text not null default 'pending_review'
    check (status in ('draft', 'pending_review', 'active', 'paused', 'ended', 'rejected')),
  moderation_status text not null default 'pending'
    check (moderation_status in ('pending', 'approved', 'rejected')),
  payment_status text not null default 'not_required'
    check (payment_status in ('not_required', 'ready', 'paid', 'failed', 'refunded')),
  daily_impression_cap integer not null default 3 check (daily_impression_cap between 1 and 20),
  total_impression_cap integer not null default 30 check (total_impression_cap between 1 and 500),
  last_delivery_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check (ends_at > starts_at)
);

create table if not exists public.explore_ad_events (
  id bigint generated by default as identity primary key,
  campaign_id uuid not null references public.explore_ad_campaigns(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null check (event_type in (
    'impression', 'view', 'click', 'profile_visit', 'video_view', 'watch',
    'complete', 'like', 'comment', 'share', 'save', 'follow', 'hide', 'report', 'mute'
  )),
  surface text not null check (surface in ('urfeed', 'swip')),
  value numeric(12, 3) not null default 1 check (value >= 0),
  completion_rate numeric(6, 5) check (completion_rate between 0 and 1),
  session_key text check (session_key is null or char_length(session_key) <= 128),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.explore_ad_user_controls (
  user_id uuid not null references auth.users(id) on delete cascade,
  campaign_id uuid not null references public.explore_ad_campaigns(id) on delete cascade,
  advertiser_id uuid not null references auth.users(id) on delete cascade,
  action text not null check (action in ('hide', 'report', 'mute_advertiser')),
  reason text check (reason is null or char_length(reason) <= 500),
  created_at timestamptz not null default timezone('utc', now()),
  primary key (user_id, campaign_id, action)
);

comment on table public.explore_ad_campaigns is
  'Explore-only campaign delivery configuration. The linked Explore post is the moderated native creative shell.';
comment on table public.explore_ad_events is
  'Privacy-safe advert analytics. No contacts, precise location, IP address, or device identifier is collected.';

create index if not exists explore_ad_campaigns_delivery_idx
  on public.explore_ad_campaigns (status, placement, starts_at, ends_at, last_delivery_at);
create index if not exists explore_ad_campaigns_advertiser_idx
  on public.explore_ad_campaigns (advertiser_id, created_at desc);
create index if not exists explore_ad_campaigns_interests_idx
  on public.explore_ad_campaigns using gin (interest_categories);
create index if not exists explore_ad_events_frequency_idx
  on public.explore_ad_events (user_id, campaign_id, event_type, created_at desc);
create index if not exists explore_ad_events_campaign_analytics_idx
  on public.explore_ad_events (campaign_id, event_type, created_at desc);
create unique index if not exists explore_ad_events_session_dedupe_idx
  on public.explore_ad_events (campaign_id, user_id, event_type, surface, session_key)
  where session_key is not null and event_type in ('impression', 'view', 'video_view');
create index if not exists explore_ad_user_controls_advertiser_idx
  on public.explore_ad_user_controls (user_id, advertiser_id, action);

alter table public.explore_ad_campaigns enable row level security;
alter table public.explore_ad_events enable row level security;
alter table public.explore_ad_user_controls enable row level security;

drop policy if exists "Advertisers read own campaigns" on public.explore_ad_campaigns;
create policy "Advertisers read own campaigns"
on public.explore_ad_campaigns for select to authenticated
using (auth.uid() = advertiser_id);

drop policy if exists "Users read own advert events" on public.explore_ad_events;
create policy "Users read own advert events"
on public.explore_ad_events for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users read own advert controls" on public.explore_ad_user_controls;
create policy "Users read own advert controls"
on public.explore_ad_user_controls for select to authenticated
using (auth.uid() = user_id);

create or replace function public.explore_force_advert_public()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.post_type = 'advert'
    or new.category = 'advert'
    or coalesce(new.media_meta, '{}'::jsonb) ? 'advert'
  then
    new.post_type := 'advert';
    new.category := 'advert';
    new.post_privacy := 'public';
  end if;
  return new;
end;
$$;

drop trigger if exists explore_force_advert_public_trigger on public.explore_posts;
create trigger explore_force_advert_public_trigger
before insert or update of post_type, category, post_privacy, media_meta
on public.explore_posts
for each row execute function public.explore_force_advert_public();

create or replace function public.create_explore_ad_campaign(
  p_post_id uuid,
  p_placement text default 'urfeed',
  p_objective text default 'brand_awareness',
  p_audience_type text default 'recommended',
  p_minimum_age integer default 13,
  p_maximum_age integer default null,
  p_gender_target text default 'all',
  p_interest_categories text[] default '{}',
  p_target_area text default null,
  p_duration_days integer default 14,
  p_starts_at timestamptz default null,
  p_ends_at timestamptz default null,
  p_budget_type text default 'total',
  p_budget_amount numeric default 0,
  p_currency text default 'SLE'
)
returns public.explore_ad_campaigns
language plpgsql
security definer
set search_path = public
as $$
declare
  v_post public.explore_posts;
  v_start timestamptz := coalesce(p_starts_at, timezone('utc', now()));
  v_end timestamptz;
  v_campaign public.explore_ad_campaigns;
  v_post_safe boolean;
begin
  select * into v_post from public.explore_posts where id = p_post_id;
  if v_post.id is null or v_post.user_id is distinct from auth.uid() then
    raise exception 'Advertisement creative was not found or is not owned by the current user';
  end if;

  if not (v_post.post_type = 'advert' or v_post.category = 'advert' or coalesce(v_post.media_meta, '{}'::jsonb) ? 'advert') then
    raise exception 'Only Explore advertisement creatives can create campaigns';
  end if;

  if p_placement in ('swip', 'both') and nullif(btrim(coalesce(v_post.video_url, '')), '') is null then
    raise exception 'Swip placement requires a reviewed video';
  end if;

  if p_placement in ('urfeed', 'both')
    and nullif(btrim(coalesce(v_post.video_url, '')), '') is not null
    and nullif(btrim(coalesce(v_post.image_url, '')), '') is null
  then
    raise exception 'UrFeed placement for a video advertisement requires an image';
  end if;

  v_end := coalesce(p_ends_at, v_start + make_interval(days => greatest(1, least(coalesce(p_duration_days, 14), 365))));
  v_post_safe := coalesce(v_post.moderation_status, 'not_required') in ('not_required', 'approved', 'legacy');

  insert into public.explore_ad_campaigns (
    creative_post_id, advertiser_id, placement, objective, audience_type,
    minimum_age, maximum_age, gender_target, interest_categories, target_area,
    duration_days, starts_at, ends_at, budget_type, budget_amount, currency,
    status, moderation_status, updated_at
  ) values (
    v_post.id, auth.uid(), lower(coalesce(p_placement, 'urfeed')),
    lower(coalesce(p_objective, 'brand_awareness')),
    lower(coalesce(p_audience_type, 'recommended')),
    greatest(13, least(coalesce(p_minimum_age, 13), 120)),
    case when p_maximum_age is null then null else greatest(coalesce(p_minimum_age, 13), least(p_maximum_age, 120)) end,
    lower(coalesce(p_gender_target, 'all')),
    coalesce(p_interest_categories, '{}'::text[]), nullif(btrim(coalesce(p_target_area, '')), ''),
    greatest(1, least(coalesce(p_duration_days, 14), 365)), v_start, v_end,
    lower(coalesce(p_budget_type, 'total')), greatest(0, coalesce(p_budget_amount, 0)),
    upper(coalesce(nullif(btrim(p_currency), ''), 'SLE')),
    case when v_post_safe then 'active' else 'pending_review' end,
    case when v_post_safe then 'approved' else 'pending' end,
    timezone('utc', now())
  )
  on conflict (creative_post_id) do update set
    placement = excluded.placement,
    objective = excluded.objective,
    audience_type = excluded.audience_type,
    minimum_age = excluded.minimum_age,
    maximum_age = excluded.maximum_age,
    gender_target = excluded.gender_target,
    interest_categories = excluded.interest_categories,
    target_area = excluded.target_area,
    duration_days = excluded.duration_days,
    starts_at = excluded.starts_at,
    ends_at = excluded.ends_at,
    budget_type = excluded.budget_type,
    budget_amount = excluded.budget_amount,
    currency = excluded.currency,
    status = excluded.status,
    moderation_status = excluded.moderation_status,
    updated_at = timezone('utc', now())
  returning * into v_campaign;

  update public.explore_posts
  set post_privacy = 'public', post_type = 'advert', category = 'advert'
  where id = v_post.id;

  return v_campaign;
end;
$$;

create or replace function public.get_recommended_explore_ads(
  p_user_id uuid,
  p_surface text default 'urfeed',
  p_limit integer default 6
)
returns table (
  campaign_id uuid,
  post_id uuid,
  score double precision,
  reason text,
  campaign jsonb
)
language sql
stable
security definer
set search_path = public
as $$
  with viewer as (
    select
      users.id,
      case
        when coalesce(
          nullif(users.raw_user_meta_data->>'date_of_birth', ''),
          nullif(users.raw_user_meta_data->>'birth_date', ''),
          ''
        )
          ~ '^\d{4}-\d{2}-\d{2}$'
        then extract(year from age(
          current_date,
          to_date(coalesce(
            nullif(users.raw_user_meta_data->>'date_of_birth', ''),
            nullif(users.raw_user_meta_data->>'birth_date', '')
          ), 'YYYY-MM-DD')
        ))::integer
        else null
      end as viewer_age,
      lower(coalesce(users.raw_user_meta_data->>'gender', '')) as viewer_gender
    from auth.users users
    where users.id = p_user_id and auth.uid() = p_user_id
  ),
  candidates as (
    select
      ad.*,
      post.likes_count,
      post.comments_count,
      post.saves_count,
      coalesce(personal.impressions, 0) as prior_impressions,
      coalesce(personal.watch_time_seconds, 0) as watch_seconds,
      coalesce(personal.max_completion_rate, 0) as completion_rate,
      coalesce(personal.skips, 0) as skips,
      coalesce(personal.hides, 0) as hides,
      coalesce(personal.reports, 0) as reports,
      coalesce(creator.interaction_score, 0) as creator_score,
      coalesce(topic_match.topic_score, 0) as topic_score,
      coalesce(topic_match.match_count, 0) as topic_matches,
      exists (
        select 1 from public.explore_follows follow
        where follow.follower_id = p_user_id and follow.following_id = ad.advertiser_id
      ) as follows_advertiser,
      frequency.today_count,
      frequency.total_count
    from public.explore_ad_campaigns ad
    join public.explore_posts post on post.id = ad.creative_post_id
    cross join viewer
    left join public.explore_content_signals personal
      on personal.user_id = p_user_id and personal.post_id = ad.creative_post_id
    left join public.explore_creator_interactions creator
      on creator.user_id = p_user_id and creator.creator_id = ad.advertiser_id
    left join lateral (
      select
        count(*)::integer as match_count,
        coalesce(sum(greatest(interest.interest_score, 0)), 0)::double precision as topic_score
      from public.explore_topic_interests interest
      where interest.user_id = p_user_id
        and lower(interest.topic) = any(coalesce(ad.interest_categories, '{}'::text[]))
    ) topic_match on true
    left join lateral (
      select
        count(*) filter (where event.created_at >= date_trunc('day', timezone('utc', now())))::integer as today_count,
        count(*)::integer as total_count
      from public.explore_ad_events event
      where event.user_id = p_user_id
        and event.campaign_id = ad.id
        and event.event_type = 'impression'
    ) frequency on true
    where ad.status = 'active'
      and ad.moderation_status = 'approved'
      and ad.starts_at <= timezone('utc', now())
      and ad.ends_at > timezone('utc', now())
      and ad.advertiser_id <> p_user_id
      and coalesce(post.post_privacy, 'public') = 'public'
      and post.post_type = 'advert'
      and post.category = 'advert'
      and post.moderation_status in ('not_required', 'approved', 'legacy')
      and (
        (lower(p_surface) = 'urfeed' and ad.placement in ('urfeed', 'both')
          and (nullif(btrim(coalesce(post.video_url, '')), '') is null or nullif(btrim(coalesce(post.image_url, '')), '') is not null))
        or
        (lower(p_surface) = 'swip' and ad.placement in ('swip', 'both')
          and nullif(btrim(coalesce(post.video_url, '')), '') is not null)
      )
      and not exists (
        select 1 from public.explore_user_blocks block
        where (block.blocker_id = p_user_id and block.blocked_id = ad.advertiser_id)
           or (block.blocker_id = ad.advertiser_id and block.blocked_id = p_user_id)
      )
      and not exists (
        select 1 from public.explore_post_reports report
        where report.post_id = post.id and report.status in ('open', 'reviewed')
      )
      and not exists (
        select 1 from public.explore_ad_user_controls control
        where control.user_id = p_user_id
          and (
            control.campaign_id = ad.id
            or (control.advertiser_id = ad.advertiser_id and control.action = 'mute_advertiser')
          )
      )
      and (
        ad.minimum_age <= 13
        or (viewer.viewer_age is not null and viewer.viewer_age >= ad.minimum_age)
      )
      and (
        ad.maximum_age is null
        or (viewer.viewer_age is not null and viewer.viewer_age <= ad.maximum_age)
      )
      and (
        ad.gender_target = 'all'
        or (viewer.viewer_gender <> '' and viewer.viewer_gender = ad.gender_target)
      )
      and (
        ad.audience_type in ('everyone', 'recommended')
        or (ad.audience_type = 'followers' and exists (
          select 1 from public.explore_follows f where f.follower_id = p_user_id and f.following_id = ad.advertiser_id
        ))
        or (ad.audience_type = 'followers_similar' and (
          exists (select 1 from public.explore_follows f where f.follower_id = p_user_id and f.following_id = ad.advertiser_id)
          or coalesce(creator.interaction_score, 0) > 0
          or coalesce(topic_match.match_count, 0) > 0
        ))
        or (ad.audience_type = 'nearby' and exists (
          select 1 from public.explore_recommendation_privacy location
          where location.user_id = p_user_id
            and location.location_personalization_enabled = true
            and nullif(btrim(coalesce(ad.target_area, '')), '') is not null
            and (
              lower(location.coarse_city) = lower(ad.target_area)
              or lower(location.coarse_area) = lower(ad.target_area)
            )
        ))
      )
      and frequency.today_count < ad.daily_impression_cap
      and frequency.total_count < ad.total_impression_cap
      and frequency.total_count <= ceil(
        ad.total_impression_cap * least(
          1,
          greatest(
            0.15,
            extract(epoch from (timezone('utc', now()) - ad.starts_at))
              / greatest(extract(epoch from (ad.ends_at - ad.starts_at)), 1)
              + 0.15
          )
        )
      )
  ),
  scored as (
    select candidate.*,
      (
        35
        + least(24, candidate.topic_score * 0.8)
        + least(18, greatest(-18, candidate.creator_score * 0.22))
        + case when candidate.follows_advertiser then 12 else 0 end
        + case when candidate.audience_type = 'recommended' then 5 else 0 end
        + case when candidate.prior_impressions = 0 then 12 else 0 end
        + least(12, candidate.completion_rate * 12)
        + least(8, candidate.watch_seconds * 0.35)
        + ln(1 + greatest(candidate.likes_count, 0)) * 1.2
        + ln(1 + greatest(candidate.comments_count, 0)) * 1.6
        + ln(1 + greatest(candidate.saves_count, 0)) * 2.0
        - least(candidate.skips, 3) * 12
        - least(candidate.hides + candidate.reports, 1) * 80
        - candidate.today_count * 14
        - candidate.total_count * 1.5
      )::double precision as delivery_score
    from candidates candidate
  )
  select
    ranked.id,
    ranked.creative_post_id,
    ranked.delivery_score,
    case
      when ranked.follows_advertiser then 'You follow this advertiser'
      when ranked.topic_matches > 0 then 'Matched to topics you engage with'
      when ranked.audience_type = 'nearby' then 'Relevant to an area you chose to personalize'
      when ranked.audience_type = 'recommended' then 'Recommended from your Explore activity'
      else 'Promoted across KunThai Explore'
    end,
    jsonb_build_object(
      'id', ranked.id,
      'placement', ranked.placement,
      'objective', ranked.objective,
      'audienceType', ranked.audience_type,
      'interests', ranked.interest_categories,
      'startsAt', ranked.starts_at,
      'endsAt', ranked.ends_at,
      'reason', case
        when ranked.follows_advertiser then 'You follow this advertiser'
        when ranked.topic_matches > 0 then 'Matched to topics you engage with'
        when ranked.audience_type = 'nearby' then 'Relevant to an area you chose to personalize'
        when ranked.audience_type = 'recommended' then 'Recommended from your Explore activity'
        else 'Promoted across KunThai Explore'
      end
    )
  from scored ranked
  order by ranked.delivery_score desc, ranked.last_delivery_at nulls first, ranked.created_at desc
  limit greatest(1, least(coalesce(p_limit, 6), 12));
$$;

create or replace function public.record_explore_ad_event(
  p_campaign_id uuid,
  p_event_type text,
  p_surface text,
  p_value numeric default 1,
  p_completion_rate numeric default null,
  p_session_key text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then return false; end if;

  insert into public.explore_ad_events (
    campaign_id, user_id, event_type, surface, value, completion_rate, session_key
  )
  select
    campaign.id, auth.uid(), lower(p_event_type), lower(p_surface),
    greatest(0, least(coalesce(p_value, 1), 3600)),
    case when p_completion_rate is null then null else greatest(0, least(p_completion_rate, 1)) end,
    nullif(left(coalesce(p_session_key, ''), 128), '')
  from public.explore_ad_campaigns campaign
  where campaign.id = p_campaign_id
  on conflict do nothing;

  if lower(p_event_type) = 'impression' then
    update public.explore_ad_campaigns
    set last_delivery_at = timezone('utc', now()), updated_at = timezone('utc', now())
    where id = p_campaign_id;
  end if;

  return found;
end;
$$;

create or replace function public.set_explore_ad_user_control(
  p_campaign_id uuid,
  p_action text,
  p_reason text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null or lower(p_action) not in ('hide', 'report', 'mute_advertiser') then
    return false;
  end if;

  insert into public.explore_ad_user_controls (user_id, campaign_id, advertiser_id, action, reason)
  select auth.uid(), campaign.id, campaign.advertiser_id, lower(p_action), nullif(left(btrim(coalesce(p_reason, '')), 500), '')
  from public.explore_ad_campaigns campaign
  where campaign.id = p_campaign_id and campaign.advertiser_id <> auth.uid()
  on conflict (user_id, campaign_id, action) do update set
    reason = excluded.reason,
    created_at = timezone('utc', now());

  return found;
end;
$$;

create or replace function public.record_explore_ad_search_interest(p_topic text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_topic text := lower(btrim(coalesce(p_topic, '')));
begin
  if auth.uid() is null or v_topic not in (
    'technology', 'fashion', 'beauty', 'food', 'sports', 'music', 'entertainment',
    'education', 'business', 'travel', 'photography', 'gaming', 'news'
  ) then
    return false;
  end if;

  insert into public.explore_topic_interests (
    user_id, topic, interest_score, positive_signals, negative_signals, updated_at
  ) values (
    auth.uid(), v_topic, 2, 1, 0, timezone('utc', now())
  )
  on conflict (user_id, topic) do update set
    interest_score = least(100, public.explore_topic_interests.interest_score + 2),
    positive_signals = public.explore_topic_interests.positive_signals + 1,
    updated_at = timezone('utc', now());

  return true;
end;
$$;

create or replace function public.get_explore_ad_analytics(p_campaign_id uuid)
returns table (
  impressions bigint,
  reach bigint,
  profile_visits bigint,
  clicks bigint,
  video_views bigint,
  average_watch_time numeric,
  completion_rate numeric,
  likes integer,
  comments integer,
  shares bigint,
  saves integer,
  follows_generated bigint,
  ctr numeric
)
language sql
stable
security definer
set search_path = public
as $$
  select
    count(*) filter (where event.event_type = 'impression'),
    count(distinct event.user_id) filter (where event.event_type = 'impression'),
    count(*) filter (where event.event_type = 'profile_visit'),
    count(*) filter (where event.event_type = 'click'),
    count(*) filter (where event.event_type in ('video_view', 'view')),
    coalesce(avg(event.value) filter (where event.event_type = 'watch'), 0),
    coalesce(avg(event.completion_rate) filter (where event.event_type in ('watch', 'complete')), 0),
    post.likes_count,
    post.comments_count,
    count(*) filter (where event.event_type = 'share'),
    post.saves_count,
    count(*) filter (where event.event_type = 'follow'),
    case
      when count(*) filter (where event.event_type = 'impression') = 0 then 0
      else round(
        count(*) filter (where event.event_type = 'click')::numeric
        / count(*) filter (where event.event_type = 'impression')::numeric * 100,
        2
      )
    end
  from public.explore_ad_campaigns campaign
  join public.explore_posts post on post.id = campaign.creative_post_id
  left join public.explore_ad_events event on event.campaign_id = campaign.id
  where campaign.id = p_campaign_id and campaign.advertiser_id = auth.uid()
  group by post.likes_count, post.comments_count, post.saves_count;
$$;

create or replace function public.explore_sync_ad_campaign_moderation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.post_type = 'advert' or new.category = 'advert' then
    update public.explore_ad_campaigns
    set
      moderation_status = case
        when new.moderation_status = 'blocked' then 'rejected'
        when new.moderation_status = 'pending' then 'pending'
        else 'approved'
      end,
      status = case
        when new.moderation_status = 'blocked' then 'rejected'
        when new.moderation_status = 'pending' then 'pending_review'
        when status = 'pending_review' then 'active'
        else status
      end,
      updated_at = timezone('utc', now())
    where creative_post_id = new.id;
  end if;
  return new;
end;
$$;

drop trigger if exists explore_sync_ad_campaign_moderation_trigger on public.explore_posts;
create trigger explore_sync_ad_campaign_moderation_trigger
after update of moderation_status on public.explore_posts
for each row execute function public.explore_sync_ad_campaign_moderation();

grant execute on function public.create_explore_ad_campaign(uuid, text, text, text, integer, integer, text, text[], text, integer, timestamptz, timestamptz, text, numeric, text) to authenticated;
grant execute on function public.get_recommended_explore_ads(uuid, text, integer) to authenticated;
grant execute on function public.record_explore_ad_event(uuid, text, text, numeric, numeric, text) to authenticated;
grant execute on function public.set_explore_ad_user_control(uuid, text, text) to authenticated;
grant execute on function public.record_explore_ad_search_interest(text) to authenticated;
grant execute on function public.get_explore_ad_analytics(uuid) to authenticated;
