-- Join KunThai question catalogue.
--
-- Generated content, safe to re-run: every row is upserted on its natural key,
-- so editing a label here updates the live questionnaire without shipping the
-- app. Questions can equally be edited directly in the database, which is the
-- point of the engine.
--
-- Consent text is deliberately NOT stored here. The investment notice, the
-- recruitment notice, and the volunteer agreement live in the application code
-- so they cannot be altered by a data edit.

insert into public.join_question_definitions (
  application_type, question_key, section_key, section_title, section_description,
  section_order, question_order, label, helper, placeholder, input_type, required,
  max_length, min_value, max_value
) values
  ('investor', 'investor_type', 'applicant', 'Applicant', 'Who is applying to invest in KunThai.', 10, 10, 'Investor type', '', '', 'select', true, null, null, null),
  ('investor', 'first_name', 'applicant', 'Applicant', 'Who is applying to invest in KunThai.', 10, 20, 'Legal first name', '', '', 'short_text', true, 80, null, null),
  ('investor', 'middle_name', 'applicant', 'Applicant', 'Who is applying to invest in KunThai.', 10, 30, 'Middle name', '', '', 'short_text', false, 80, null, null),
  ('investor', 'last_name', 'applicant', 'Applicant', 'Who is applying to invest in KunThai.', 10, 40, 'Legal last name', '', '', 'short_text', true, 80, null, null),
  ('investor', 'date_of_birth', 'applicant', 'Applicant', 'Who is applying to invest in KunThai.', 10, 50, 'Date of birth', '', '', 'date', true, null, null, null),
  ('investor', 'nationality', 'applicant', 'Applicant', 'Who is applying to invest in KunThai.', 10, 60, 'Nationality', '', '', 'country', true, null, null, null),
  ('investor', 'occupation', 'applicant', 'Applicant', 'Who is applying to invest in KunThai.', 10, 70, 'Occupation', '', '', 'short_text', true, 120, null, null),
  ('investor', 'employer', 'applicant', 'Applicant', 'Who is applying to invest in KunThai.', 10, 80, 'Employer or company', '', '', 'short_text', false, 160, null, null),
  ('investor', 'entity_name', 'applicant', 'Applicant', 'Who is applying to invest in KunThai.', 10, 90, 'Legal entity name', '', '', 'short_text', true, 200, null, null),
  ('investor', 'entity_type', 'applicant', 'Applicant', 'Who is applying to invest in KunThai.', 10, 100, 'Organization type', '', '', 'select', true, null, null, null),
  ('investor', 'registration_country', 'applicant', 'Applicant', 'Who is applying to invest in KunThai.', 10, 110, 'Country of registration', '', '', 'country', true, null, null, null),
  ('investor', 'registration_number', 'applicant', 'Applicant', 'Who is applying to invest in KunThai.', 10, 120, 'Registration number', '', '', 'short_text', true, 120, null, null),
  ('investor', 'representative_name', 'applicant', 'Applicant', 'Who is applying to invest in KunThai.', 10, 130, 'Representative''s full name', '', '', 'short_text', true, 160, null, null),
  ('investor', 'representative_position', 'applicant', 'Applicant', 'Who is applying to invest in KunThai.', 10, 140, 'Representative''s position', '', '', 'short_text', true, 160, null, null),
  ('investor', 'fund_size', 'applicant', 'Applicant', 'Who is applying to invest in KunThai.', 10, 150, 'Approximate assets or fund size', 'Optional. A range is fine.', '', 'short_text', false, 120, null, null),
  ('investor', 'country', 'applicant', 'Applicant', 'Who is applying to invest in KunThai.', 10, 160, 'Country of residence or main operation', '', '', 'country', true, null, null, null),
  ('investor', 'city', 'applicant', 'Applicant', 'Who is applying to invest in KunThai.', 10, 170, 'City', '', '', 'short_text', false, 120, null, null),
  ('investor', 'email', 'applicant', 'Applicant', 'Who is applying to invest in KunThai.', 10, 180, 'Email address', '', '', 'email', true, 200, null, null),
  ('investor', 'phone', 'applicant', 'Applicant', 'Who is applying to invest in KunThai.', 10, 190, 'Phone number', '', '', 'phone', true, 40, null, null),
  ('investor', 'linkedin_url', 'applicant', 'Applicant', 'Who is applying to invest in KunThai.', 10, 200, 'LinkedIn profile', '', '', 'url', false, 300, null, null),
  ('investor', 'website_url', 'applicant', 'Applicant', 'Who is applying to invest in KunThai.', 10, 210, 'Website', '', '', 'url', false, 300, null, null),
  ('investor', 'invested_before', 'profile', 'Investment profile', 'Your experience as an investor.', 20, 10, 'Have you invested in a startup before?', '', '', 'boolean', true, null, null, null),
  ('investor', 'prior_investment_count', 'profile', 'Investment profile', 'Your experience as an investor.', 20, 20, 'Approximately how many?', '', '', 'number', false, null, 0, 10000),
  ('investor', 'prior_industries', 'profile', 'Investment profile', 'Your experience as an investor.', 20, 30, 'Which industries?', '', '', 'short_text', false, 300, null, null),
  ('investor', 'typical_ticket', 'profile', 'Investment profile', 'Your experience as an investor.', 20, 40, 'Typical investment size', '', '', 'short_text', false, 120, null, null),
  ('investor', 'earliest_stage', 'profile', 'Investment profile', 'Your experience as an investor.', 20, 50, 'Earliest stage you normally invest in', '', '', 'select', false, null, null, null),
  ('investor', 'portfolio_links', 'profile', 'Investment profile', 'Your experience as an investor.', 20, 60, 'Portfolio or company links', '', '', 'long_text', false, 1000, null, null),
  ('investor', 'investor_category', 'profile', 'Investment profile', 'Your experience as an investor.', 20, 70, 'Investor category', '', '', 'select', true, null, null, null),
  ('investor', 'areas_of_interest', 'profile', 'Investment profile', 'Your experience as an investor.', 20, 80, 'Areas of interest', '', '', 'multi_select', true, null, null, null),
  ('investor', 'investment_currency', 'proposal', 'Proposed investment', 'What you are considering, and what you would bring.', 30, 10, 'Currency', '', '', 'select', true, null, null, null),
  ('investor', 'investment_amount', 'proposal', 'Proposed investment', 'What you are considering, and what you would bring.', 30, 20, 'How much are you considering investing?', 'An indication is enough. Nothing here commits you to invest.', '', 'currency', true, null, 0, null),
  ('investor', 'investment_structure', 'proposal', 'Proposed investment', 'What you are considering, and what you would bring.', 30, 30, 'Preferred investment structure', '', '', 'select', true, null, null, null),
  ('investor', 'terms_notice', 'proposal', 'Proposed investment', 'What you are considering, and what you would bring.', 30, 40, 'Investment terms', 'Your proposed investment amount will be reviewed by KunThai. Any equity percentage, company valuation, investor rights, and investment structure would be communicated through a formal investment proposal if your application progresses.', '', 'statement', false, null, null, null),
  ('investor', 'investment_goal', 'proposal', 'Proposed investment', 'What you are considering, and what you would bring.', 30, 50, 'What are you hoping to achieve through your investment?', '', '', 'long_text', true, 2000, null, null),
  ('investor', 'contribution_types', 'proposal', 'Proposed investment', 'What you are considering, and what you would bring.', 30, 60, 'Besides capital, what could you bring to KunThai?', '', '', 'multi_select', false, null, null, null),
  ('investor', 'contribution_notes', 'proposal', 'Proposed investment', 'What you are considering, and what you would bring.', 30, 70, 'Tell us more about that contribution', '', '', 'long_text', false, 2000, null, null),
  ('investor', 'involvement', 'proposal', 'Proposed investment', 'What you are considering, and what you would bring.', 30, 80, 'Preferred involvement', '', '', 'select', true, null, null, null),
  ('investor', 'investment_timeframe', 'proposal', 'Proposed investment', 'What you are considering, and what you would bring.', 30, 90, 'Investment timeframe', '', '', 'select', true, null, null, null),
  ('investor', 'source_of_funds', 'diligence', 'Verification readiness', 'KunThai does not collect identity documents at this stage. These answers tell us what a later check would involve.', 40, 10, 'Source of investment funds', '', '', 'select', true, null, null, null),
  ('investor', 'investing_on_behalf', 'diligence', 'Verification readiness', 'KunThai does not collect identity documents at this stage. These answers tell us what a later check would involve.', 40, 20, 'Are you investing on behalf of another person or entity?', '', '', 'boolean', true, null, null, null),
  ('investor', 'beneficial_owner_details', 'diligence', 'Verification readiness', 'KunThai does not collect identity documents at this stage. These answers tell us what a later check would involve.', 40, 30, 'Who would the investment ultimately be made for?', '', '', 'long_text', false, 2000, null, null),
  ('investor', 'willing_to_verify', 'diligence', 'Verification readiness', 'KunThai does not collect identity documents at this stage. These answers tell us what a later check would involve.', 40, 40, 'Are you willing to complete identity and source-of-funds verification if required?', '', '', 'boolean', true, null, null, null),
  ('investor', 'why_kunthai', 'closing', 'Final questions', 'The part that tells us the most.', 50, 10, 'Why KunThai?', '', '', 'long_text', true, 2000, null, null),
  ('investor', 'vision_interest', 'closing', 'Final questions', 'The part that tells us the most.', 50, 20, 'What part of KunThai''s vision interests you most?', '', '', 'long_text', false, 2000, null, null),
  ('investor', 'concerns', 'closing', 'Final questions', 'The part that tells us the most.', 50, 30, 'What concerns would you want addressed before investing?', '', '', 'long_text', false, 2000, null, null),
  ('investor', 'referral_source', 'closing', 'Final questions', 'The part that tells us the most.', 50, 40, 'How did you hear about KunThai?', '', '', 'select', false, null, null, null),
  ('investor', 'anything_else', 'closing', 'Final questions', 'The part that tells us the most.', 50, 50, 'Anything else we should know?', '', '', 'long_text', false, 2000, null, null),
  ('staff', 'first_name', 'personal', 'Personal details', 'How KunThai reaches you.', 60, 10, 'First name', '', '', 'short_text', true, 80, null, null),
  ('staff', 'middle_name', 'personal', 'Personal details', 'How KunThai reaches you.', 60, 20, 'Middle name', '', '', 'short_text', false, 80, null, null),
  ('staff', 'last_name', 'personal', 'Personal details', 'How KunThai reaches you.', 60, 30, 'Last name', '', '', 'short_text', true, 80, null, null),
  ('staff', 'email', 'personal', 'Personal details', 'How KunThai reaches you.', 60, 40, 'Email address', '', '', 'email', true, 200, null, null),
  ('staff', 'phone', 'personal', 'Personal details', 'How KunThai reaches you.', 60, 50, 'Phone number', '', '', 'phone', true, 40, null, null),
  ('staff', 'country', 'personal', 'Personal details', 'How KunThai reaches you.', 60, 60, 'Country', '', '', 'country', true, null, null, null),
  ('staff', 'city', 'personal', 'Personal details', 'How KunThai reaches you.', 60, 70, 'City or region', '', '', 'short_text', true, 120, null, null),
  ('staff', 'nationality', 'personal', 'Personal details', 'How KunThai reaches you.', 60, 80, 'Nationality', '', '', 'country', false, null, null, null),
  ('staff', 'preferred_location', 'personal', 'Personal details', 'How KunThai reaches you.', 60, 90, 'Preferred working location', '', '', 'short_text', false, 160, null, null),
  ('staff', 'linkedin_url', 'personal', 'Personal details', 'How KunThai reaches you.', 60, 100, 'LinkedIn', '', '', 'url', false, 300, null, null),
  ('staff', 'github_url', 'personal', 'Personal details', 'How KunThai reaches you.', 60, 110, 'GitHub', '', '', 'url', false, 300, null, null),
  ('staff', 'portfolio_url', 'personal', 'Personal details', 'How KunThai reaches you.', 60, 120, 'Portfolio or website', '', '', 'url', false, 300, null, null),
  ('staff', 'department', 'position', 'The role', 'Where you would fit, and how you would work.', 70, 10, 'Which area would you like to join?', '', '', 'select', true, null, null, null),
  ('staff', 'department_other', 'position', 'The role', 'Where you would fit, and how you would work.', 70, 20, 'Tell us which area', '', '', 'short_text', false, 160, null, null),
  ('staff', 'employment_type', 'position', 'The role', 'Where you would fit, and how you would work.', 70, 30, 'Employment type', '', '', 'select', true, null, null, null),
  ('staff', 'work_mode', 'position', 'The role', 'Where you would fit, and how you would work.', 70, 40, 'Working arrangement', '', '', 'select', true, null, null, null),
  ('staff', 'available_from', 'position', 'The role', 'Where you would fit, and how you would work.', 70, 50, 'Available start date', '', '', 'date', false, null, null, null),
  ('staff', 'weekly_hours', 'position', 'The role', 'Where you would fit, and how you would work.', 70, 60, 'Hours available per week', '', '', 'number', false, null, 1, 80),
  ('staff', 'preferred_hours', 'position', 'The role', 'Where you would fit, and how you would work.', 70, 70, 'Preferred working hours or time zone', '', '', 'short_text', false, 160, null, null),
  ('staff', 'willing_to_travel', 'position', 'The role', 'Where you would fit, and how you would work.', 70, 80, 'Willing to travel?', '', '', 'boolean', false, null, null, null),
  ('staff', 'willing_to_relocate', 'position', 'The role', 'Where you would fit, and how you would work.', 70, 90, 'Willing to relocate?', '', '', 'boolean', false, null, null, null),
  ('staff', 'compensation_currency', 'position', 'The role', 'Where you would fit, and how you would work.', 70, 100, 'Compensation currency', '', '', 'select', false, null, null, null),
  ('staff', 'compensation_expectation', 'position', 'The role', 'Where you would fit, and how you would work.', 70, 110, 'Compensation expectation', 'Optional. A range is fine, and it will not be used to screen you out.', '', 'short_text', false, 120, null, null),
  ('staff', 'compensation_period', 'position', 'The role', 'Where you would fit, and how you would work.', 70, 120, 'Compensation period', '', '', 'select', false, null, null, null),
  ('staff', 'highest_education', 'education', 'Academic background', 'Education is one signal among several. A strong portfolio counts for as much as a degree.', 80, 10, 'Highest level of education', '', '', 'select', true, null, null, null),
  ('staff', 'certifications', 'education', 'Academic background', 'Education is one signal among several. A strong portfolio counts for as much as a degree.', 80, 20, 'Relevant certifications', '', '', 'long_text', false, 1000, null, null),
  ('staff', 'licenses', 'education', 'Academic background', 'Education is one signal among several. A strong portfolio counts for as much as a degree.', 80, 30, 'Professional licenses', '', '', 'long_text', false, 1000, null, null),
  ('staff', 'primary_strengths', 'skills', 'Knowledge and skills', 'Add each skill with an honest self-assessment.', 90, 10, 'What are you strongest at?', '', '', 'long_text', true, 2000, null, null),
  ('staff', 'eng_languages', 'technical', 'Role questions', 'These change with the area you chose.', 100, 10, 'Primary programming languages', '', '', 'short_text', true, 300, null, null),
  ('staff', 'eng_frameworks', 'technical', 'Role questions', 'These change with the area you chose.', 100, 20, 'Frameworks you work in', '', '', 'short_text', false, 300, null, null),
  ('staff', 'eng_git', 'technical', 'Role questions', 'These change with the area you chose.', 100, 30, 'Git proficiency', '', '', 'select', false, null, null, null),
  ('staff', 'eng_databases', 'technical', 'Role questions', 'These change with the area you chose.', 100, 40, 'Database experience', '', '', 'short_text', false, 300, null, null),
  ('staff', 'eng_api_experience', 'technical', 'Role questions', 'These change with the area you chose.', 100, 50, 'API development experience', '', '', 'select', false, null, null, null),
  ('staff', 'eng_testing', 'technical', 'Role questions', 'These change with the area you chose.', 100, 60, 'How do you test what you build?', '', '', 'long_text', false, 2000, null, null),
  ('staff', 'eng_production', 'technical', 'Role questions', 'These change with the area you chose.', 100, 70, 'Have you deployed and run software in production?', '', '', 'boolean', false, null, null, null),
  ('staff', 'eng_hardest_project', 'technical', 'Role questions', 'These change with the area you chose.', 100, 80, 'Describe the most technically challenging project you have worked on', '', '', 'long_text', true, 3000, null, null),
  ('staff', 'eng_contribution', 'technical', 'Role questions', 'These change with the area you chose.', 100, 90, 'What exactly was your contribution to it?', '', '', 'long_text', true, 3000, null, null),
  ('staff', 'eng_debugging', 'technical', 'Role questions', 'These change with the area you chose.', 100, 100, 'Describe a production problem you debugged', '', '', 'long_text', false, 3000, null, null),
  ('staff', 'eng_ai_assisted', 'technical', 'Role questions', 'These change with the area you chose.', 100, 110, 'Experience with AI-assisted coding', '', '', 'select', false, null, null, null),
  ('staff', 'eng_focus', 'technical', 'Role questions', 'These change with the area you chose.', 100, 120, 'Where do you do your best work?', '', '', 'select', false, null, null, null),
  ('staff', 'ml_python', 'technical', 'Role questions', 'These change with the area you chose.', 100, 130, 'Python proficiency', '', '', 'select', true, null, null, null),
  ('staff', 'ml_frameworks', 'technical', 'Role questions', 'These change with the area you chose.', 100, 140, 'Frameworks you have used', '', '', 'multi_select', false, null, null, null),
  ('staff', 'ml_llm', 'technical', 'Role questions', 'These change with the area you chose.', 100, 150, 'Your experience with large language models', '', '', 'long_text', false, 3000, null, null),
  ('staff', 'ml_domains', 'technical', 'Role questions', 'These change with the area you chose.', 100, 160, 'Domains you have worked in', '', '', 'multi_select', false, null, null, null),
  ('staff', 'ml_evaluation', 'technical', 'Role questions', 'These change with the area you chose.', 100, 170, 'How do you evaluate a model before trusting it?', '', '', 'long_text', false, 3000, null, null),
  ('staff', 'ml_infrastructure', 'technical', 'Role questions', 'These change with the area you chose.', 100, 180, 'Compute you have worked with', '', '', 'select', false, null, null, null),
  ('staff', 'ml_pipelines', 'technical', 'Role questions', 'These change with the area you chose.', 100, 190, 'Data pipeline experience', '', '', 'long_text', false, 2000, null, null),
  ('staff', 'ml_deployment', 'technical', 'Role questions', 'These change with the area you chose.', 100, 200, 'Have you deployed a model into a product?', '', '', 'long_text', false, 2000, null, null),
  ('staff', 'ml_projects', 'technical', 'Role questions', 'These change with the area you chose.', 100, 210, 'Relevant projects, papers, or repositories', '', '', 'long_text', false, 2000, null, null),
  ('staff', 'sec_domains', 'technical', 'Role questions', 'These change with the area you chose.', 100, 220, 'Security areas you work in', '', '', 'multi_select', false, null, null, null),
  ('staff', 'sec_incident', 'technical', 'Role questions', 'These change with the area you chose.', 100, 230, 'Describe a security issue you found or handled', '', '', 'long_text', true, 3000, null, null),
  ('staff', 'sec_tooling', 'technical', 'Role questions', 'These change with the area you chose.', 100, 240, 'Tools you rely on', '', '', 'short_text', false, 300, null, null),
  ('staff', 'sec_certifications', 'technical', 'Role questions', 'These change with the area you chose.', 100, 250, 'Security certifications', '', '', 'short_text', false, 300, null, null),
  ('staff', 'fin_qualifications', 'technical', 'Role questions', 'These change with the area you chose.', 100, 260, 'Accounting or finance qualifications', '', '', 'short_text', false, 300, null, null),
  ('staff', 'fin_accounting', 'technical', 'Role questions', 'These change with the area you chose.', 100, 270, 'Accounting proficiency', '', '', 'select', false, null, null, null),
  ('staff', 'fin_modelling', 'technical', 'Role questions', 'These change with the area you chose.', 100, 280, 'Financial modelling and budgeting experience', '', '', 'long_text', false, 3000, null, null),
  ('staff', 'fin_payments', 'technical', 'Role questions', 'These change with the area you chose.', 100, 290, 'Payments or fintech experience', '', '', 'long_text', false, 3000, null, null),
  ('staff', 'fin_reconciliation', 'technical', 'Role questions', 'These change with the area you chose.', 100, 300, 'How would you approach reconciling a high volume of small transactions?', '', '', 'long_text', false, 3000, null, null),
  ('staff', 'fin_risk', 'technical', 'Role questions', 'These change with the area you chose.', 100, 310, 'Financial risk and controls experience', '', '', 'long_text', false, 2000, null, null),
  ('staff', 'fin_tools', 'technical', 'Role questions', 'These change with the area you chose.', 100, 320, 'Finance tools and systems you know', '', '', 'short_text', false, 300, null, null),
  ('staff', 'legal_jurisdictions', 'technical', 'Role questions', 'These change with the area you chose.', 100, 330, 'Jurisdictions you are qualified or experienced in', '', '', 'short_text', true, 300, null, null),
  ('staff', 'legal_qualifications', 'technical', 'Role questions', 'These change with the area you chose.', 100, 340, 'Legal qualifications', '', '', 'short_text', false, 300, null, null),
  ('staff', 'legal_corporate', 'technical', 'Role questions', 'These change with the area you chose.', 100, 350, 'Corporate and company law experience', '', '', 'long_text', false, 3000, null, null),
  ('staff', 'legal_privacy', 'technical', 'Role questions', 'These change with the area you chose.', 100, 360, 'Data protection and privacy experience', '', '', 'long_text', false, 3000, null, null),
  ('staff', 'legal_fintech', 'technical', 'Role questions', 'These change with the area you chose.', 100, 370, 'Fintech and payments regulation experience', '', '', 'long_text', false, 3000, null, null),
  ('staff', 'legal_aml', 'technical', 'Role questions', 'These change with the area you chose.', 100, 380, 'AML and KYC experience', '', '', 'long_text', false, 3000, null, null),
  ('staff', 'legal_securities', 'technical', 'Role questions', 'These change with the area you chose.', 100, 390, 'Securities and investment law experience', '', '', 'long_text', false, 3000, null, null),
  ('staff', 'legal_contracts', 'technical', 'Role questions', 'These change with the area you chose.', 100, 400, 'Contract drafting and negotiation experience', '', '', 'long_text', false, 3000, null, null),
  ('staff', 'design_tools', 'technical', 'Role questions', 'These change with the area you chose.', 100, 410, 'Design tools you work in', '', '', 'multi_select', false, null, null, null),
  ('staff', 'design_research', 'technical', 'Role questions', 'These change with the area you chose.', 100, 420, 'How do you learn what users actually need?', '', '', 'long_text', false, 3000, null, null),
  ('staff', 'design_prototyping', 'technical', 'Role questions', 'These change with the area you chose.', 100, 430, 'Prototyping experience', '', '', 'long_text', false, 2000, null, null),
  ('staff', 'design_systems', 'technical', 'Role questions', 'These change with the area you chose.', 100, 440, 'Design system experience', '', '', 'long_text', false, 2000, null, null),
  ('staff', 'design_accessibility', 'technical', 'Role questions', 'These change with the area you chose.', 100, 450, 'How do you handle accessibility?', '', '', 'long_text', false, 2000, null, null),
  ('staff', 'design_portfolio', 'technical', 'Role questions', 'These change with the area you chose.', 100, 460, 'Portfolio link', '', '', 'url', true, 300, null, null),
  ('staff', 'ts_moderation', 'technical', 'Role questions', 'These change with the area you chose.', 100, 470, 'Content moderation or trust and safety experience', '', '', 'long_text', true, 3000, null, null),
  ('staff', 'ts_policy', 'technical', 'Role questions', 'These change with the area you chose.', 100, 480, 'How would you write a policy that is fair and enforceable?', '', '', 'long_text', false, 3000, null, null),
  ('staff', 'ts_escalation', 'technical', 'Role questions', 'These change with the area you chose.', 100, 490, 'Describe how you would handle an urgent safety report', '', '', 'long_text', false, 3000, null, null),
  ('staff', 'ts_wellbeing', 'technical', 'Role questions', 'These change with the area you chose.', 100, 500, 'How do you look after yourself doing difficult review work?', '', '', 'long_text', false, 2000, null, null),
  ('staff', 'pm_discovery', 'technical', 'Role questions', 'These change with the area you chose.', 100, 510, 'How do you decide what to build?', '', '', 'long_text', true, 3000, null, null),
  ('staff', 'pm_metrics', 'technical', 'Role questions', 'These change with the area you chose.', 100, 520, 'Which metrics do you trust, and which mislead?', '', '', 'long_text', false, 3000, null, null),
  ('staff', 'pm_shipped', 'technical', 'Role questions', 'These change with the area you chose.', 100, 530, 'Describe something you shipped end to end', '', '', 'long_text', false, 3000, null, null),
  ('staff', 'pm_prioritisation', 'technical', 'Role questions', 'These change with the area you chose.', 100, 540, 'How do you prioritise when everything is urgent?', '', '', 'long_text', false, 2000, null, null),
  ('staff', 'gtm_channels', 'technical', 'Role questions', 'These change with the area you chose.', 100, 550, 'Channels you have worked in', '', '', 'multi_select', false, null, null, null),
  ('staff', 'gtm_campaign', 'technical', 'Role questions', 'These change with the area you chose.', 100, 560, 'Describe a campaign or partnership you ran', '', '', 'long_text', true, 3000, null, null),
  ('staff', 'gtm_metrics', 'technical', 'Role questions', 'These change with the area you chose.', 100, 570, 'What results did it produce, and how did you measure them?', '', '', 'long_text', false, 2000, null, null),
  ('staff', 'ops_scale', 'technical', 'Role questions', 'These change with the area you chose.', 100, 580, 'Describe an operation you ran and its scale', '', '', 'long_text', true, 3000, null, null),
  ('staff', 'ops_process', 'technical', 'Role questions', 'These change with the area you chose.', 100, 590, 'Describe a process you improved', '', '', 'long_text', false, 3000, null, null),
  ('staff', 'ops_tools', 'technical', 'Role questions', 'These change with the area you chose.', 100, 600, 'Tools and systems you have used', '', '', 'short_text', false, 300, null, null),
  ('staff', 'currently_employed', 'experience', 'Professional experience', 'Roles, and the work you are proudest of.', 110, 10, 'Are you currently employed?', '', '', 'boolean', true, null, null, null),
  ('staff', 'current_employer', 'experience', 'Professional experience', 'Roles, and the work you are proudest of.', 110, 20, 'Current organization', '', '', 'short_text', false, 200, null, null),
  ('staff', 'current_position', 'experience', 'Professional experience', 'Roles, and the work you are proudest of.', 110, 30, 'Current position', '', '', 'short_text', false, 200, null, null),
  ('staff', 'may_contact_employer', 'experience', 'Professional experience', 'Roles, and the work you are proudest of.', 110, 40, 'May KunThai contact this employer?', '', '', 'boolean', false, null, null, null),
  ('staff', 'total_experience', 'experience', 'Professional experience', 'Roles, and the work you are proudest of.', 110, 50, 'Total professional experience', '', '', 'select', true, null, null, null),
  ('staff', 'startup_experience', 'experience', 'Professional experience', 'Roles, and the work you are proudest of.', 110, 60, 'Have you worked at a startup before?', '', '', 'boolean', true, null, null, null),
  ('staff', 'startup_stage', 'experience', 'Professional experience', 'Roles, and the work you are proudest of.', 110, 70, 'At what stage was it?', '', '', 'select', false, null, null, null),
  ('staff', 'startup_learning', 'experience', 'Professional experience', 'Roles, and the work you are proudest of.', 110, 80, 'What did you learn there?', '', '', 'long_text', false, 3000, null, null),
  ('staff', 'proudest_work', 'experience', 'Professional experience', 'Roles, and the work you are proudest of.', 110, 90, 'Describe the project or accomplishment you are most proud of', '', '', 'long_text', true, 3000, null, null),
  ('staff', 'difficult_problem', 'experience', 'Professional experience', 'Roles, and the work you are proudest of.', 110, 100, 'Describe a difficult problem you solved', '', '', 'long_text', true, 3000, null, null),
  ('staff', 'why_kunthai', 'kunthai', 'About KunThai', 'These answers usually tell us more than a CV does.', 120, 10, 'Why do you want to join KunThai?', '', '', 'long_text', true, 3000, null, null),
  ('staff', 'understanding_kunthai', 'kunthai', 'About KunThai', 'These answers usually tell us more than a CV does.', 120, 20, 'What do you understand about KunThai?', '', '', 'long_text', true, 3000, null, null),
  ('staff', 'product_interest', 'kunthai', 'About KunThai', 'These answers usually tell us more than a CV does.', 120, 30, 'Which part of KunThai interests you most?', '', '', 'select', true, null, null, null),
  ('staff', 'problem_to_solve', 'kunthai', 'About KunThai', 'These answers usually tell us more than a CV does.', 120, 40, 'What problem should KunThai solve better than anyone else?', '', '', 'long_text', false, 3000, null, null),
  ('staff', 'first_improvement', 'kunthai', 'About KunThai', 'These answers usually tell us more than a CV does.', 120, 50, 'If you joined tomorrow, what would you try to improve first?', '', '', 'long_text', false, 3000, null, null),
  ('staff', 'first_90_days', 'kunthai', 'About KunThai', 'These answers usually tell us more than a CV does.', 120, 60, 'What could you contribute in your first 90 days?', '', '', 'long_text', true, 3000, null, null),
  ('staff', 'three_year_goal', 'kunthai', 'About KunThai', 'These answers usually tell us more than a CV does.', 120, 70, 'Where would you like to be professionally in three years?', '', '', 'long_text', false, 2000, null, null),
  ('staff', 'referral_source', 'kunthai', 'About KunThai', 'These answers usually tell us more than a CV does.', 120, 80, 'How did you hear about KunThai?', '', '', 'select', false, null, null, null),
  ('staff', 'documents_notice', 'documents', 'Documents', 'A CV helps, but it is not the only thing we read. Do not upload identity documents at this stage.', 130, 10, 'What to attach', 'Attach a CV or resume, and anything that shows your work: a cover letter, certificates, or a portfolio. Identity checks happen later in the process, through a secure channel.', '', 'statement', false, null, null, null),
  ('volunteer', 'first_name', 'personal', 'Personal details', 'How KunThai reaches you.', 140, 10, 'First name', '', '', 'short_text', true, 80, null, null),
  ('volunteer', 'middle_name', 'personal', 'Personal details', 'How KunThai reaches you.', 140, 20, 'Middle name', '', '', 'short_text', false, 80, null, null),
  ('volunteer', 'last_name', 'personal', 'Personal details', 'How KunThai reaches you.', 140, 30, 'Last name', '', '', 'short_text', true, 80, null, null),
  ('volunteer', 'email', 'personal', 'Personal details', 'How KunThai reaches you.', 140, 40, 'Email address', '', '', 'email', true, 200, null, null),
  ('volunteer', 'phone', 'personal', 'Personal details', 'How KunThai reaches you.', 140, 50, 'Phone number', '', '', 'phone', true, 40, null, null),
  ('volunteer', 'country', 'personal', 'Personal details', 'How KunThai reaches you.', 140, 60, 'Country', '', '', 'country', true, null, null, null),
  ('volunteer', 'city', 'personal', 'Personal details', 'How KunThai reaches you.', 140, 70, 'City or region', '', '', 'short_text', false, 120, null, null),
  ('volunteer', 'nationality', 'personal', 'Personal details', 'How KunThai reaches you.', 140, 80, 'Nationality', '', '', 'country', false, null, null, null),
  ('volunteer', 'linkedin_url', 'personal', 'Personal details', 'How KunThai reaches you.', 140, 90, 'LinkedIn', '', '', 'url', false, 300, null, null),
  ('volunteer', 'portfolio_url', 'personal', 'Personal details', 'How KunThai reaches you.', 140, 100, 'Portfolio or website', '', '', 'url', false, 300, null, null),
  ('volunteer', 'volunteer_areas', 'contribution', 'What you would contribute', 'Choose the areas you can genuinely help with.', 150, 10, 'Where would you like to help?', '', '', 'multi_select', true, null, null, null),
  ('volunteer', 'volunteer_skills_detail', 'contribution', 'What you would contribute', 'Choose the areas you can genuinely help with.', 150, 20, 'Tell us what you can do in those areas', '', '', 'long_text', true, 3000, null, null),
  ('volunteer', 'highest_education', 'contribution', 'What you would contribute', 'Choose the areas you can genuinely help with.', 150, 30, 'Highest level of education', '', '', 'select', false, null, null, null),
  ('volunteer', 'vol_dev_details', 'contribution', 'What you would contribute', 'Choose the areas you can genuinely help with.', 150, 40, 'What have you built, and in what languages?', '', '', 'long_text', false, 3000, null, null),
  ('volunteer', 'vol_dev_repo', 'contribution', 'What you would contribute', 'Choose the areas you can genuinely help with.', 150, 50, 'Repository or project link', '', '', 'url', false, 300, null, null),
  ('volunteer', 'vol_design_portfolio', 'contribution', 'What you would contribute', 'Choose the areas you can genuinely help with.', 150, 60, 'Design portfolio link', '', '', 'url', false, 300, null, null),
  ('volunteer', 'vol_languages', 'contribution', 'What you would contribute', 'Choose the areas you can genuinely help with.', 150, 70, 'Which languages can you translate between?', '', '', 'short_text', false, 300, null, null),
  ('volunteer', 'vol_content_samples', 'contribution', 'What you would contribute', 'Choose the areas you can genuinely help with.', 150, 80, 'Links to content you have made', '', '', 'long_text', false, 2000, null, null),
  ('volunteer', 'vol_ai_details', 'contribution', 'What you would contribute', 'Choose the areas you can genuinely help with.', 150, 90, 'What AI or data work have you done?', '', '', 'long_text', false, 3000, null, null),
  ('volunteer', 'vol_ts_details', 'contribution', 'What you would contribute', 'Choose the areas you can genuinely help with.', 150, 100, 'Why do you want to work on Trust and Safety?', '', '', 'long_text', false, 3000, null, null),
  ('volunteer', 'weekly_commitment', 'commitment', 'Time you can give', 'Be realistic. A small reliable commitment beats a large uncertain one.', 160, 10, 'How much time can you commit each week?', '', '', 'select', true, null, null, null),
  ('volunteer', 'commitment_length', 'commitment', 'Time you can give', 'Be realistic. A small reliable commitment beats a large uncertain one.', 160, 20, 'Preferred commitment', '', '', 'select', true, null, null, null),
  ('volunteer', 'available_from', 'commitment', 'Time you can give', 'Be realistic. A small reliable commitment beats a large uncertain one.', 160, 30, 'Available from', '', '', 'date', false, null, null, null),
  ('volunteer', 'preferred_hours', 'commitment', 'Time you can give', 'Be realistic. A small reliable commitment beats a large uncertain one.', 160, 40, 'Preferred hours or time zone', '', '', 'short_text', false, 160, null, null),
  ('volunteer', 'why_volunteer', 'motivation', 'Motivation', 'Why this, and why now.', 170, 10, 'Why do you want to volunteer with KunThai?', '', '', 'long_text', true, 3000, null, null),
  ('volunteer', 'why_select_you', 'motivation', 'Motivation', 'Why this, and why now.', 170, 20, 'Why should KunThai select you?', '', '', 'long_text', true, 3000, null, null),
  ('volunteer', 'what_to_learn', 'motivation', 'Motivation', 'Why this, and why now.', 170, 30, 'What would you like to learn while working with KunThai?', '', '', 'long_text', false, 2000, null, null),
  ('volunteer', 'open_to_paid', 'motivation', 'Motivation', 'Why this, and why now.', 170, 40, 'Would you consider a paid position in the future?', '', '', 'select', true, null, null, null),
  ('volunteer', 'referral_source', 'motivation', 'Motivation', 'Why this, and why now.', 170, 50, 'How did you hear about KunThai?', '', '', 'select', false, null, null, null)
on conflict (application_type, question_key) do update
set section_key = excluded.section_key,
    section_title = excluded.section_title,
    section_description = excluded.section_description,
    section_order = excluded.section_order,
    question_order = excluded.question_order,
    label = excluded.label,
    helper = excluded.helper,
    placeholder = excluded.placeholder,
    input_type = excluded.input_type,
    required = excluded.required,
    max_length = excluded.max_length,
    min_value = excluded.min_value,
    max_value = excluded.max_value,
    active = true;

insert into public.join_question_options (application_type, question_key, value, label, option_order) values
  ('investor', 'investor_type', 'individual', 'Individual', 10),
  ('investor', 'investor_type', 'company', 'Company', 20),
  ('investor', 'investor_type', 'fund', 'Investment fund', 30),
  ('investor', 'investor_type', 'angel', 'Angel investor', 40),
  ('investor', 'investor_type', 'vc', 'Venture capital firm', 50),
  ('investor', 'investor_type', 'family_office', 'Family office', 60),
  ('investor', 'investor_type', 'other', 'Other', 70),
  ('investor', 'entity_type', 'private_company', 'Private company', 10),
  ('investor', 'entity_type', 'public_company', 'Public company', 20),
  ('investor', 'entity_type', 'fund', 'Investment fund', 30),
  ('investor', 'entity_type', 'vc', 'Venture capital firm', 40),
  ('investor', 'entity_type', 'family_office', 'Family office', 50),
  ('investor', 'entity_type', 'trust', 'Trust', 60),
  ('investor', 'entity_type', 'other', 'Other', 70),
  ('investor', 'earliest_stage', 'idea', 'Idea stage', 10),
  ('investor', 'earliest_stage', 'pre_seed', 'Pre-seed', 20),
  ('investor', 'earliest_stage', 'seed', 'Seed', 30),
  ('investor', 'earliest_stage', 'series_a', 'Series A', 40),
  ('investor', 'earliest_stage', 'growth', 'Growth', 50),
  ('investor', 'earliest_stage', 'any', 'Any stage', 60),
  ('investor', 'investor_category', 'first_time', 'First-time investor', 10),
  ('investor', 'investor_category', 'angel', 'Angel investor', 20),
  ('investor', 'investor_category', 'strategic', 'Strategic investor', 30),
  ('investor', 'investor_category', 'institutional', 'Institutional investor', 40),
  ('investor', 'investor_category', 'vc', 'Venture capital', 50),
  ('investor', 'investor_category', 'corporate', 'Corporate investor', 60),
  ('investor', 'investor_category', 'other', 'Other', 70),
  ('investor', 'areas_of_interest', 'fintech', 'Fintech', 10),
  ('investor', 'areas_of_interest', 'social_community', 'Social and community', 20),
  ('investor', 'areas_of_interest', 'ecommerce', 'E-commerce', 30),
  ('investor', 'areas_of_interest', 'mobility', 'Transportation and mobility', 40),
  ('investor', 'areas_of_interest', 'creator_economy', 'Creator economy', 50),
  ('investor', 'areas_of_interest', 'ai', 'AI', 60),
  ('investor', 'areas_of_interest', 'african_technology', 'African technology', 70),
  ('investor', 'areas_of_interest', 'payments', 'Payments', 80),
  ('investor', 'areas_of_interest', 'other', 'Other', 90),
  ('investor', 'investment_currency', 'USD', 'USD', 10),
  ('investor', 'investment_currency', 'EUR', 'EUR', 20),
  ('investor', 'investment_currency', 'GBP', 'GBP', 30),
  ('investor', 'investment_currency', 'SLE', 'SLE', 40),
  ('investor', 'investment_currency', 'other', 'Another currency', 50),
  ('investor', 'investment_structure', 'equity', 'Equity', 10),
  ('investor', 'investment_structure', 'safe', 'SAFE or similar future-equity instrument', 20),
  ('investor', 'investment_structure', 'convertible', 'Convertible instrument', 30),
  ('investor', 'investment_structure', 'strategic', 'Strategic investment or partnership', 40),
  ('investor', 'investment_structure', 'open', 'Open to KunThai''s recommendation', 50),
  ('investor', 'investment_structure', 'unsure', 'Not sure yet', 60),
  ('investor', 'contribution_types', 'industry_expertise', 'Industry expertise', 10),
  ('investor', 'contribution_types', 'technical_expertise', 'Technical expertise', 20),
  ('investor', 'contribution_types', 'business_development', 'Business development', 30),
  ('investor', 'contribution_types', 'financial_expertise', 'Financial expertise', 40),
  ('investor', 'contribution_types', 'regulatory_knowledge', 'Regulatory knowledge', 50),
  ('investor', 'contribution_types', 'african_market_access', 'African market access', 60),
  ('investor', 'contribution_types', 'international_expansion', 'International expansion', 70),
  ('investor', 'contribution_types', 'partnerships', 'Partnerships', 80),
  ('investor', 'contribution_types', 'mentorship', 'Mentorship', 90),
  ('investor', 'contribution_types', 'investor_network', 'Investor network', 100),
  ('investor', 'contribution_types', 'other', 'Other', 110),
  ('investor', 'involvement', 'passive', 'Passive investor', 10),
  ('investor', 'involvement', 'adviser', 'Strategic adviser', 20),
  ('investor', 'involvement', 'active', 'Active strategic investor', 30),
  ('investor', 'involvement', 'discuss', 'Open to discussion', 40),
  ('investor', 'investment_timeframe', 'immediately', 'Immediately', 10),
  ('investor', 'investment_timeframe', 'within_30_days', 'Within 30 days', 20),
  ('investor', 'investment_timeframe', '1_3_months', '1 to 3 months', 30),
  ('investor', 'investment_timeframe', '3_6_months', '3 to 6 months', 40),
  ('investor', 'investment_timeframe', 'exploring', 'Exploring only', 50),
  ('investor', 'source_of_funds', 'employment_income', 'Employment or business income', 10),
  ('investor', 'source_of_funds', 'business_profits', 'Business profits', 20),
  ('investor', 'source_of_funds', 'investment_proceeds', 'Investment proceeds', 30),
  ('investor', 'source_of_funds', 'savings', 'Savings', 40),
  ('investor', 'source_of_funds', 'institutional_capital', 'Institutional or fund capital', 50),
  ('investor', 'source_of_funds', 'other', 'Other', 60),
  ('investor', 'referral_source', 'explore', 'Inside KunThai', 10),
  ('investor', 'referral_source', 'friend', 'Someone told me', 20),
  ('investor', 'referral_source', 'social_media', 'Social media', 30),
  ('investor', 'referral_source', 'news', 'News or article', 40),
  ('investor', 'referral_source', 'event', 'An event', 50),
  ('investor', 'referral_source', 'search', 'Web search', 60),
  ('investor', 'referral_source', 'other', 'Somewhere else', 70),
  ('staff', 'department', 'software_engineering', 'Software Engineering', 10),
  ('staff', 'department', 'mobile', 'Mobile Development', 20),
  ('staff', 'department', 'backend', 'Backend Engineering', 30),
  ('staff', 'department', 'frontend', 'Frontend Engineering', 40),
  ('staff', 'department', 'devops', 'DevOps and Cloud', 50),
  ('staff', 'department', 'cybersecurity', 'Cybersecurity', 60),
  ('staff', 'department', 'ai_ml', 'AI and Machine Learning', 70),
  ('staff', 'department', 'trust_safety', 'Trust and Safety', 80),
  ('staff', 'department', 'design', 'UI and UX Design', 90),
  ('staff', 'department', 'product', 'Product Management', 100),
  ('staff', 'department', 'finance', 'Finance', 110),
  ('staff', 'department', 'legal_compliance', 'Legal and Compliance', 120),
  ('staff', 'department', 'operations', 'Operations', 130),
  ('staff', 'department', 'marketing', 'Marketing', 140),
  ('staff', 'department', 'sales', 'Sales', 150),
  ('staff', 'department', 'support', 'Customer Support', 160),
  ('staff', 'department', 'people', 'Human Resources', 170),
  ('staff', 'department', 'partnerships', 'Partnerships', 180),
  ('staff', 'department', 'content', 'Content and Creator Relations', 190),
  ('staff', 'department', 'urride_operations', 'UrRide Operations', 200),
  ('staff', 'department', 'urmall_operations', 'UrMall Operations', 210),
  ('staff', 'department', 'other', 'Other', 220),
  ('staff', 'employment_type', 'full_time', 'Full-time', 10),
  ('staff', 'employment_type', 'part_time', 'Part-time', 20),
  ('staff', 'employment_type', 'contract', 'Contract', 30),
  ('staff', 'employment_type', 'internship', 'Internship', 40),
  ('staff', 'work_mode', 'remote', 'Remote', 10),
  ('staff', 'work_mode', 'hybrid', 'Hybrid', 20),
  ('staff', 'work_mode', 'on_site', 'On-site', 30),
  ('staff', 'compensation_currency', 'USD', 'USD', 10),
  ('staff', 'compensation_currency', 'EUR', 'EUR', 20),
  ('staff', 'compensation_currency', 'GBP', 'GBP', 30),
  ('staff', 'compensation_currency', 'SLE', 'SLE', 40),
  ('staff', 'compensation_currency', 'other', 'Another currency', 50),
  ('staff', 'compensation_period', 'hourly', 'Per hour', 10),
  ('staff', 'compensation_period', 'monthly', 'Per month', 20),
  ('staff', 'compensation_period', 'yearly', 'Per year', 30),
  ('staff', 'compensation_period', 'project', 'Per project', 40),
  ('staff', 'highest_education', 'none', 'No formal qualification', 10),
  ('staff', 'highest_education', 'secondary', 'Secondary or high school', 20),
  ('staff', 'highest_education', 'certificate', 'Certificate', 30),
  ('staff', 'highest_education', 'diploma', 'Diploma', 40),
  ('staff', 'highest_education', 'bachelors', 'Bachelor''s degree', 50),
  ('staff', 'highest_education', 'postgraduate_diploma', 'Postgraduate diploma', 60),
  ('staff', 'highest_education', 'masters', 'Master''s degree', 70),
  ('staff', 'highest_education', 'doctorate', 'Doctorate or PhD', 80),
  ('staff', 'highest_education', 'professional', 'Professional qualification', 90),
  ('staff', 'highest_education', 'studying', 'Currently studying', 100),
  ('staff', 'highest_education', 'other', 'Other', 110),
  ('staff', 'eng_git', 'beginner', 'Beginner', 10),
  ('staff', 'eng_git', 'basic', 'Basic', 20),
  ('staff', 'eng_git', 'intermediate', 'Intermediate', 30),
  ('staff', 'eng_git', 'advanced', 'Advanced', 40),
  ('staff', 'eng_git', 'expert', 'Expert', 50),
  ('staff', 'eng_api_experience', 'beginner', 'Beginner', 10),
  ('staff', 'eng_api_experience', 'basic', 'Basic', 20),
  ('staff', 'eng_api_experience', 'intermediate', 'Intermediate', 30),
  ('staff', 'eng_api_experience', 'advanced', 'Advanced', 40),
  ('staff', 'eng_api_experience', 'expert', 'Expert', 50),
  ('staff', 'eng_ai_assisted', 'none', 'None', 10),
  ('staff', 'eng_ai_assisted', 'some', 'Occasionally', 20),
  ('staff', 'eng_ai_assisted', 'regular', 'Regularly', 30),
  ('staff', 'eng_ai_assisted', 'heavy', 'Daily, as part of how I work', 40),
  ('staff', 'eng_focus', 'frontend', 'Frontend', 10),
  ('staff', 'eng_focus', 'backend', 'Backend', 20),
  ('staff', 'eng_focus', 'full_stack', 'Full-stack', 30),
  ('staff', 'eng_focus', 'mobile', 'Mobile', 40),
  ('staff', 'eng_focus', 'infrastructure', 'Infrastructure', 50),
  ('staff', 'ml_python', 'beginner', 'Beginner', 10),
  ('staff', 'ml_python', 'basic', 'Basic', 20),
  ('staff', 'ml_python', 'intermediate', 'Intermediate', 30),
  ('staff', 'ml_python', 'advanced', 'Advanced', 40),
  ('staff', 'ml_python', 'expert', 'Expert', 50),
  ('staff', 'ml_frameworks', 'pytorch', 'PyTorch', 10),
  ('staff', 'ml_frameworks', 'tensorflow', 'TensorFlow', 20),
  ('staff', 'ml_frameworks', 'jax', 'JAX', 30),
  ('staff', 'ml_frameworks', 'scikit_learn', 'scikit-learn', 40),
  ('staff', 'ml_frameworks', 'hugging_face', 'Hugging Face', 50),
  ('staff', 'ml_frameworks', 'other', 'Other', 60),
  ('staff', 'ml_domains', 'cv', 'Computer vision', 10),
  ('staff', 'ml_domains', 'nlp', 'Natural language processing', 20),
  ('staff', 'ml_domains', 'speech', 'Speech', 30),
  ('staff', 'ml_domains', 'recsys', 'Recommendation systems', 40),
  ('staff', 'ml_domains', 'tabular', 'Tabular and classical ML', 50),
  ('staff', 'ml_domains', 'other', 'Other', 60),
  ('staff', 'ml_infrastructure', 'none', 'None yet', 10),
  ('staff', 'ml_infrastructure', 'colab', 'Hosted notebooks', 20),
  ('staff', 'ml_infrastructure', 'single_gpu', 'A single GPU', 30),
  ('staff', 'ml_infrastructure', 'multi_gpu', 'Multiple GPUs', 40),
  ('staff', 'ml_infrastructure', 'cloud_cluster', 'Cloud clusters', 50),
  ('staff', 'sec_domains', 'appsec', 'Application security', 10),
  ('staff', 'sec_domains', 'infrastructure', 'Infrastructure and cloud security', 20),
  ('staff', 'sec_domains', 'incident_response', 'Incident response', 30),
  ('staff', 'sec_domains', 'fraud', 'Fraud and abuse', 40),
  ('staff', 'sec_domains', 'identity', 'Identity and access', 50),
  ('staff', 'sec_domains', 'privacy', 'Privacy engineering', 60),
  ('staff', 'sec_domains', 'other', 'Other', 70),
  ('staff', 'fin_accounting', 'beginner', 'Beginner', 10),
  ('staff', 'fin_accounting', 'basic', 'Basic', 20),
  ('staff', 'fin_accounting', 'intermediate', 'Intermediate', 30),
  ('staff', 'fin_accounting', 'advanced', 'Advanced', 40),
  ('staff', 'fin_accounting', 'expert', 'Expert', 50),
  ('staff', 'design_tools', 'figma', 'Figma', 10),
  ('staff', 'design_tools', 'sketch', 'Sketch', 20),
  ('staff', 'design_tools', 'adobe_xd', 'Adobe XD', 30),
  ('staff', 'design_tools', 'penpot', 'Penpot', 40),
  ('staff', 'design_tools', 'illustrator', 'Illustrator', 50),
  ('staff', 'design_tools', 'photoshop', 'Photoshop', 60),
  ('staff', 'design_tools', 'other', 'Other', 70),
  ('staff', 'gtm_channels', 'social', 'Social media', 10),
  ('staff', 'gtm_channels', 'content', 'Content and SEO', 20),
  ('staff', 'gtm_channels', 'paid', 'Paid acquisition', 30),
  ('staff', 'gtm_channels', 'community', 'Community', 40),
  ('staff', 'gtm_channels', 'partnerships', 'Partnerships', 50),
  ('staff', 'gtm_channels', 'field', 'Field and events', 60),
  ('staff', 'gtm_channels', 'direct_sales', 'Direct sales', 70),
  ('staff', 'gtm_channels', 'other', 'Other', 80),
  ('staff', 'total_experience', 'none', 'None yet', 10),
  ('staff', 'total_experience', 'under_1', 'Less than 1 year', 20),
  ('staff', 'total_experience', '1_2', '1 to 2 years', 30),
  ('staff', 'total_experience', '3_5', '3 to 5 years', 40),
  ('staff', 'total_experience', '6_10', '6 to 10 years', 50),
  ('staff', 'total_experience', '10_plus', 'More than 10 years', 60),
  ('staff', 'startup_stage', 'idea', 'Idea stage', 10),
  ('staff', 'startup_stage', 'pre_seed', 'Pre-seed', 20),
  ('staff', 'startup_stage', 'seed', 'Seed', 30),
  ('staff', 'startup_stage', 'series_a', 'Series A or later', 40),
  ('staff', 'startup_stage', 'growth', 'Growth', 50),
  ('staff', 'product_interest', 'explore', 'Explore', 10),
  ('staff', 'product_interest', 'urfeed_swip', 'UrFeed and Swip', 20),
  ('staff', 'product_interest', 'urmall', 'UrMall', 30),
  ('staff', 'product_interest', 'urride', 'UrRide', 40),
  ('staff', 'product_interest', 'kunthaimoney', 'KunThaiMoney', 50),
  ('staff', 'product_interest', 'trust_safety', 'Trust and Safety', 60),
  ('staff', 'product_interest', 'platform', 'Platform and infrastructure', 70),
  ('staff', 'product_interest', 'whole_ecosystem', 'The whole ecosystem', 80),
  ('staff', 'referral_source', 'explore', 'Inside KunThai', 10),
  ('staff', 'referral_source', 'friend', 'Someone told me', 20),
  ('staff', 'referral_source', 'social_media', 'Social media', 30),
  ('staff', 'referral_source', 'news', 'News or article', 40),
  ('staff', 'referral_source', 'event', 'An event', 50),
  ('staff', 'referral_source', 'search', 'Web search', 60),
  ('staff', 'referral_source', 'other', 'Somewhere else', 70),
  ('volunteer', 'volunteer_areas', 'software_development', 'Software development', 10),
  ('volunteer', 'volunteer_areas', 'design', 'UI and UX design', 20),
  ('volunteer', 'volunteer_areas', 'testing', 'Testing and QA', 30),
  ('volunteer', 'volunteer_areas', 'community', 'Community', 40),
  ('volunteer', 'volunteer_areas', 'content', 'Content', 50),
  ('volunteer', 'volunteer_areas', 'marketing', 'Marketing', 60),
  ('volunteer', 'volunteer_areas', 'social_media', 'Social media', 70),
  ('volunteer', 'volunteer_areas', 'support', 'Customer support', 80),
  ('volunteer', 'volunteer_areas', 'translation', 'Translation', 90),
  ('volunteer', 'volunteer_areas', 'research', 'Research', 100),
  ('volunteer', 'volunteer_areas', 'ai', 'AI', 110),
  ('volunteer', 'volunteer_areas', 'data', 'Data', 120),
  ('volunteer', 'volunteer_areas', 'trust_safety', 'Trust and Safety', 130),
  ('volunteer', 'volunteer_areas', 'operations', 'Operations', 140),
  ('volunteer', 'volunteer_areas', 'finance', 'Finance', 150),
  ('volunteer', 'volunteer_areas', 'legal', 'Legal', 160),
  ('volunteer', 'volunteer_areas', 'business_development', 'Business development', 170),
  ('volunteer', 'volunteer_areas', 'other', 'Other', 180),
  ('volunteer', 'highest_education', 'none', 'No formal qualification', 10),
  ('volunteer', 'highest_education', 'secondary', 'Secondary or high school', 20),
  ('volunteer', 'highest_education', 'certificate', 'Certificate', 30),
  ('volunteer', 'highest_education', 'diploma', 'Diploma', 40),
  ('volunteer', 'highest_education', 'bachelors', 'Bachelor''s degree', 50),
  ('volunteer', 'highest_education', 'postgraduate_diploma', 'Postgraduate diploma', 60),
  ('volunteer', 'highest_education', 'masters', 'Master''s degree', 70),
  ('volunteer', 'highest_education', 'doctorate', 'Doctorate or PhD', 80),
  ('volunteer', 'highest_education', 'professional', 'Professional qualification', 90),
  ('volunteer', 'highest_education', 'studying', 'Currently studying', 100),
  ('volunteer', 'highest_education', 'other', 'Other', 110),
  ('volunteer', 'weekly_commitment', 'under_5', 'Less than 5 hours', 10),
  ('volunteer', 'weekly_commitment', '5_10', '5 to 10 hours', 20),
  ('volunteer', 'weekly_commitment', '10_20', '10 to 20 hours', 30),
  ('volunteer', 'weekly_commitment', '20_plus', 'More than 20 hours', 40),
  ('volunteer', 'commitment_length', 'under_1_month', 'Less than a month', 10),
  ('volunteer', 'commitment_length', '1_3_months', '1 to 3 months', 20),
  ('volunteer', 'commitment_length', '3_6_months', '3 to 6 months', 30),
  ('volunteer', 'commitment_length', '6_12_months', '6 to 12 months', 40),
  ('volunteer', 'commitment_length', 'long_term', 'Long term', 50),
  ('volunteer', 'open_to_paid', 'yes', 'Yes', 10),
  ('volunteer', 'open_to_paid', 'no', 'No', 20),
  ('volunteer', 'open_to_paid', 'maybe', 'Maybe', 30),
  ('volunteer', 'referral_source', 'explore', 'Inside KunThai', 10),
  ('volunteer', 'referral_source', 'friend', 'Someone told me', 20),
  ('volunteer', 'referral_source', 'social_media', 'Social media', 30),
  ('volunteer', 'referral_source', 'news', 'News or article', 40),
  ('volunteer', 'referral_source', 'event', 'An event', 50),
  ('volunteer', 'referral_source', 'search', 'Web search', 60),
  ('volunteer', 'referral_source', 'other', 'Somewhere else', 70)
on conflict (application_type, question_key, value) do update
set label = excluded.label,
    option_order = excluded.option_order,
    active = true;

insert into public.join_conditional_rules (application_type, question_key, match_mode, conditions) values
  ('investor', 'first_name', 'all', '[{"key":"investor_type","op":"in","value":["individual","angel"]}]'::jsonb),
  ('investor', 'middle_name', 'all', '[{"key":"investor_type","op":"in","value":["individual","angel"]}]'::jsonb),
  ('investor', 'last_name', 'all', '[{"key":"investor_type","op":"in","value":["individual","angel"]}]'::jsonb),
  ('investor', 'date_of_birth', 'all', '[{"key":"investor_type","op":"in","value":["individual","angel"]}]'::jsonb),
  ('investor', 'nationality', 'all', '[{"key":"investor_type","op":"in","value":["individual","angel"]}]'::jsonb),
  ('investor', 'occupation', 'all', '[{"key":"investor_type","op":"in","value":["individual","angel"]}]'::jsonb),
  ('investor', 'employer', 'all', '[{"key":"investor_type","op":"in","value":["individual","angel"]}]'::jsonb),
  ('investor', 'entity_name', 'all', '[{"key":"investor_type","op":"in","value":["company","fund","vc","family_office","other"]}]'::jsonb),
  ('investor', 'entity_type', 'all', '[{"key":"investor_type","op":"in","value":["company","fund","vc","family_office","other"]}]'::jsonb),
  ('investor', 'registration_country', 'all', '[{"key":"investor_type","op":"in","value":["company","fund","vc","family_office","other"]}]'::jsonb),
  ('investor', 'registration_number', 'all', '[{"key":"investor_type","op":"in","value":["company","fund","vc","family_office","other"]}]'::jsonb),
  ('investor', 'representative_name', 'all', '[{"key":"investor_type","op":"in","value":["company","fund","vc","family_office","other"]}]'::jsonb),
  ('investor', 'representative_position', 'all', '[{"key":"investor_type","op":"in","value":["company","fund","vc","family_office","other"]}]'::jsonb),
  ('investor', 'fund_size', 'all', '[{"key":"investor_type","op":"in","value":["company","fund","vc","family_office","other"]}]'::jsonb),
  ('investor', 'prior_investment_count', 'all', '[{"key":"invested_before","op":"is_true"}]'::jsonb),
  ('investor', 'prior_industries', 'all', '[{"key":"invested_before","op":"is_true"}]'::jsonb),
  ('investor', 'typical_ticket', 'all', '[{"key":"invested_before","op":"is_true"}]'::jsonb),
  ('investor', 'earliest_stage', 'all', '[{"key":"invested_before","op":"is_true"}]'::jsonb),
  ('investor', 'portfolio_links', 'all', '[{"key":"invested_before","op":"is_true"}]'::jsonb),
  ('investor', 'beneficial_owner_details', 'all', '[{"key":"investing_on_behalf","op":"is_true"}]'::jsonb),
  ('staff', 'department_other', 'all', '[{"key":"department","op":"eq","value":"other"}]'::jsonb),
  ('staff', 'eng_languages', 'all', '[{"key":"department","op":"in","value":["software_engineering","mobile","backend","frontend","devops"]}]'::jsonb),
  ('staff', 'eng_frameworks', 'all', '[{"key":"department","op":"in","value":["software_engineering","mobile","backend","frontend","devops"]}]'::jsonb),
  ('staff', 'eng_git', 'all', '[{"key":"department","op":"in","value":["software_engineering","mobile","backend","frontend","devops"]}]'::jsonb),
  ('staff', 'eng_databases', 'all', '[{"key":"department","op":"in","value":["software_engineering","mobile","backend","frontend","devops"]}]'::jsonb),
  ('staff', 'eng_api_experience', 'all', '[{"key":"department","op":"in","value":["software_engineering","mobile","backend","frontend","devops"]}]'::jsonb),
  ('staff', 'eng_testing', 'all', '[{"key":"department","op":"in","value":["software_engineering","mobile","backend","frontend","devops"]}]'::jsonb),
  ('staff', 'eng_production', 'all', '[{"key":"department","op":"in","value":["software_engineering","mobile","backend","frontend","devops"]}]'::jsonb),
  ('staff', 'eng_hardest_project', 'all', '[{"key":"department","op":"in","value":["software_engineering","mobile","backend","frontend","devops"]}]'::jsonb),
  ('staff', 'eng_contribution', 'all', '[{"key":"department","op":"in","value":["software_engineering","mobile","backend","frontend","devops"]}]'::jsonb),
  ('staff', 'eng_debugging', 'all', '[{"key":"department","op":"in","value":["software_engineering","mobile","backend","frontend","devops"]}]'::jsonb),
  ('staff', 'eng_ai_assisted', 'all', '[{"key":"department","op":"in","value":["software_engineering","mobile","backend","frontend","devops"]}]'::jsonb),
  ('staff', 'eng_focus', 'all', '[{"key":"department","op":"in","value":["software_engineering","mobile","backend","frontend","devops"]}]'::jsonb),
  ('staff', 'ml_python', 'all', '[{"key":"department","op":"eq","value":"ai_ml"}]'::jsonb),
  ('staff', 'ml_frameworks', 'all', '[{"key":"department","op":"eq","value":"ai_ml"}]'::jsonb),
  ('staff', 'ml_llm', 'all', '[{"key":"department","op":"eq","value":"ai_ml"}]'::jsonb),
  ('staff', 'ml_domains', 'all', '[{"key":"department","op":"eq","value":"ai_ml"}]'::jsonb),
  ('staff', 'ml_evaluation', 'all', '[{"key":"department","op":"eq","value":"ai_ml"}]'::jsonb),
  ('staff', 'ml_infrastructure', 'all', '[{"key":"department","op":"eq","value":"ai_ml"}]'::jsonb),
  ('staff', 'ml_pipelines', 'all', '[{"key":"department","op":"eq","value":"ai_ml"}]'::jsonb),
  ('staff', 'ml_deployment', 'all', '[{"key":"department","op":"eq","value":"ai_ml"}]'::jsonb),
  ('staff', 'ml_projects', 'all', '[{"key":"department","op":"eq","value":"ai_ml"}]'::jsonb),
  ('staff', 'sec_domains', 'all', '[{"key":"department","op":"eq","value":"cybersecurity"}]'::jsonb),
  ('staff', 'sec_incident', 'all', '[{"key":"department","op":"eq","value":"cybersecurity"}]'::jsonb),
  ('staff', 'sec_tooling', 'all', '[{"key":"department","op":"eq","value":"cybersecurity"}]'::jsonb),
  ('staff', 'sec_certifications', 'all', '[{"key":"department","op":"eq","value":"cybersecurity"}]'::jsonb),
  ('staff', 'fin_qualifications', 'all', '[{"key":"department","op":"eq","value":"finance"}]'::jsonb),
  ('staff', 'fin_accounting', 'all', '[{"key":"department","op":"eq","value":"finance"}]'::jsonb),
  ('staff', 'fin_modelling', 'all', '[{"key":"department","op":"eq","value":"finance"}]'::jsonb),
  ('staff', 'fin_payments', 'all', '[{"key":"department","op":"eq","value":"finance"}]'::jsonb),
  ('staff', 'fin_reconciliation', 'all', '[{"key":"department","op":"eq","value":"finance"}]'::jsonb),
  ('staff', 'fin_risk', 'all', '[{"key":"department","op":"eq","value":"finance"}]'::jsonb),
  ('staff', 'fin_tools', 'all', '[{"key":"department","op":"eq","value":"finance"}]'::jsonb),
  ('staff', 'legal_jurisdictions', 'all', '[{"key":"department","op":"eq","value":"legal_compliance"}]'::jsonb),
  ('staff', 'legal_qualifications', 'all', '[{"key":"department","op":"eq","value":"legal_compliance"}]'::jsonb),
  ('staff', 'legal_corporate', 'all', '[{"key":"department","op":"eq","value":"legal_compliance"}]'::jsonb),
  ('staff', 'legal_privacy', 'all', '[{"key":"department","op":"eq","value":"legal_compliance"}]'::jsonb),
  ('staff', 'legal_fintech', 'all', '[{"key":"department","op":"eq","value":"legal_compliance"}]'::jsonb),
  ('staff', 'legal_aml', 'all', '[{"key":"department","op":"eq","value":"legal_compliance"}]'::jsonb),
  ('staff', 'legal_securities', 'all', '[{"key":"department","op":"eq","value":"legal_compliance"}]'::jsonb),
  ('staff', 'legal_contracts', 'all', '[{"key":"department","op":"eq","value":"legal_compliance"}]'::jsonb),
  ('staff', 'design_tools', 'all', '[{"key":"department","op":"eq","value":"design"}]'::jsonb),
  ('staff', 'design_research', 'all', '[{"key":"department","op":"eq","value":"design"}]'::jsonb),
  ('staff', 'design_prototyping', 'all', '[{"key":"department","op":"eq","value":"design"}]'::jsonb),
  ('staff', 'design_systems', 'all', '[{"key":"department","op":"eq","value":"design"}]'::jsonb),
  ('staff', 'design_accessibility', 'all', '[{"key":"department","op":"eq","value":"design"}]'::jsonb),
  ('staff', 'design_portfolio', 'all', '[{"key":"department","op":"eq","value":"design"}]'::jsonb),
  ('staff', 'ts_moderation', 'all', '[{"key":"department","op":"eq","value":"trust_safety"}]'::jsonb),
  ('staff', 'ts_policy', 'all', '[{"key":"department","op":"eq","value":"trust_safety"}]'::jsonb),
  ('staff', 'ts_escalation', 'all', '[{"key":"department","op":"eq","value":"trust_safety"}]'::jsonb),
  ('staff', 'ts_wellbeing', 'all', '[{"key":"department","op":"eq","value":"trust_safety"}]'::jsonb),
  ('staff', 'pm_discovery', 'all', '[{"key":"department","op":"eq","value":"product"}]'::jsonb),
  ('staff', 'pm_metrics', 'all', '[{"key":"department","op":"eq","value":"product"}]'::jsonb),
  ('staff', 'pm_shipped', 'all', '[{"key":"department","op":"eq","value":"product"}]'::jsonb),
  ('staff', 'pm_prioritisation', 'all', '[{"key":"department","op":"eq","value":"product"}]'::jsonb),
  ('staff', 'gtm_channels', 'all', '[{"key":"department","op":"in","value":["marketing","sales","content","partnerships"]}]'::jsonb),
  ('staff', 'gtm_campaign', 'all', '[{"key":"department","op":"in","value":["marketing","sales","content","partnerships"]}]'::jsonb),
  ('staff', 'gtm_metrics', 'all', '[{"key":"department","op":"in","value":["marketing","sales","content","partnerships"]}]'::jsonb),
  ('staff', 'ops_scale', 'all', '[{"key":"department","op":"in","value":["operations","support","people","urride_operations","urmall_operations"]}]'::jsonb),
  ('staff', 'ops_process', 'all', '[{"key":"department","op":"in","value":["operations","support","people","urride_operations","urmall_operations"]}]'::jsonb),
  ('staff', 'ops_tools', 'all', '[{"key":"department","op":"in","value":["operations","support","people","urride_operations","urmall_operations"]}]'::jsonb),
  ('staff', 'current_employer', 'all', '[{"key":"currently_employed","op":"is_true"}]'::jsonb),
  ('staff', 'current_position', 'all', '[{"key":"currently_employed","op":"is_true"}]'::jsonb),
  ('staff', 'may_contact_employer', 'all', '[{"key":"currently_employed","op":"is_true"}]'::jsonb),
  ('staff', 'startup_stage', 'all', '[{"key":"startup_experience","op":"is_true"}]'::jsonb),
  ('staff', 'startup_learning', 'all', '[{"key":"startup_experience","op":"is_true"}]'::jsonb),
  ('volunteer', 'vol_dev_details', 'all', '[{"key":"volunteer_areas","op":"contains","value":"software_development"}]'::jsonb),
  ('volunteer', 'vol_dev_repo', 'all', '[{"key":"volunteer_areas","op":"contains","value":"software_development"}]'::jsonb),
  ('volunteer', 'vol_design_portfolio', 'all', '[{"key":"volunteer_areas","op":"contains","value":"design"}]'::jsonb),
  ('volunteer', 'vol_languages', 'all', '[{"key":"volunteer_areas","op":"contains","value":"translation"}]'::jsonb),
  ('volunteer', 'vol_content_samples', 'any', '[{"key":"volunteer_areas","op":"contains","value":"content"},{"key":"volunteer_areas","op":"contains","value":"social_media"},{"key":"volunteer_areas","op":"contains","value":"marketing"}]'::jsonb),
  ('volunteer', 'vol_ai_details', 'any', '[{"key":"volunteer_areas","op":"contains","value":"ai"},{"key":"volunteer_areas","op":"contains","value":"data"}]'::jsonb),
  ('volunteer', 'vol_ts_details', 'all', '[{"key":"volunteer_areas","op":"contains","value":"trust_safety"}]'::jsonb)
on conflict (application_type, question_key) do update
set match_mode = excluded.match_mode,
    conditions = excluded.conditions,
    active = true;
