-- Canonical KunThai account identities and secure account recovery.
-- Public clients can use only the two narrow RPCs granted at the end.

create extension if not exists pgcrypto;

create or replace function public.normalize_kunthai_email(input_email text)
returns text
language sql
immutable
set search_path = pg_catalog
as $$
  select nullif(lower(btrim(coalesce(input_email, ''))), '');
$$;

create or replace function public.normalize_kunthai_phone(input_phone text, country_hint text default null)
returns text
language plpgsql
immutable
set search_path = pg_catalog
as $$
declare
  raw_phone text := btrim(coalesce(input_phone, ''));
  phone_digits text := regexp_replace(coalesce(input_phone, ''), '[^0-9]', '', 'g');
  hint_key text := upper(regexp_replace(coalesce(country_hint, ''), '[^A-Za-z0-9]', '', 'g'));
  dial_digits text := '';
begin
  if raw_phone = '' or phone_digits = '' then
    return null;
  end if;

  dial_digits := case hint_key
    when 'SL' then '232'
    when 'SIERRALEONE' then '232'
    when 'LR' then '231'
    when 'LIBERIA' then '231'
    when 'GH' then '233'
    when 'GHANA' then '233'
    when 'NG' then '234'
    when 'NIGERIA' then '234'
    when 'GN' then '224'
    when 'GUINEA' then '224'
    when 'CI' then '225'
    when 'IVORYCOAST' then '225'
    when 'COTEDIVOIRE' then '225'
    when 'SN' then '221'
    when 'SENEGAL' then '221'
    when 'GM' then '220'
    when 'THEGAMBIA' then '220'
    when 'GAMBIA' then '220'
    when 'ML' then '223'
    when 'MALI' then '223'
    when 'BF' then '226'
    when 'BURKINAFASO' then '226'
    when 'BJ' then '229'
    when 'BENIN' then '229'
    when 'TG' then '228'
    when 'TOGO' then '228'
    when 'NE' then '227'
    when 'NIGER' then '227'
    when 'GW' then '245'
    when 'GUINEABISSAU' then '245'
    when 'CV' then '238'
    when 'CAPEVERDE' then '238'
    when 'CABOVERDE' then '238'
    when 'MR' then '222'
    when 'MAURITANIA' then '222'
    when 'MAURITANIE' then '222'
    else ''
  end;

  if raw_phone ~ '^\s*\+' then
    null;
  elsif raw_phone ~ '^\s*00' then
    phone_digits := substring(phone_digits from 3);
  elsif dial_digits <> '' and phone_digits not like dial_digits || '%' then
    phone_digits := dial_digits || regexp_replace(phone_digits, '^0+', '');
  else
    phone_digits := regexp_replace(phone_digits, '^0+', '');
  end if;

  if length(phone_digits) < 8 or length(phone_digits) > 15 then
    return null;
  end if;

  return '+' || phone_digits;
end;
$$;

create or replace function public.kunthai_hash_identity(input_value text)
returns text
language sql
immutable
set search_path = extensions, public, pg_catalog
as $$
  select encode(digest(coalesce(input_value, ''), 'sha256'), 'hex');
$$;

create table if not exists public.kunthai_account_identities (
  user_id uuid primary key references auth.users(id) on delete cascade,
  normalized_email text,
  normalized_phone text,
  display_name text not null default 'KunThai account',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint kunthai_identity_email_is_normalized check (
    normalized_email is null or normalized_email = public.normalize_kunthai_email(normalized_email)
  ),
  constraint kunthai_identity_phone_is_normalized check (
    normalized_phone is null or normalized_phone = public.normalize_kunthai_phone(normalized_phone, null)
  )
);

create unique index if not exists kunthai_account_identities_email_uidx
  on public.kunthai_account_identities (normalized_email)
  where normalized_email is not null;

create unique index if not exists kunthai_account_identities_phone_uidx
  on public.kunthai_account_identities (normalized_phone)
  where normalized_phone is not null;

create table if not exists public.kunthai_account_identity_conflicts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  conflict_type text not null check (conflict_type in ('email', 'phone')),
  identity_hash text not null,
  detected_at timestamptz not null default now()
);

create unique index if not exists kunthai_account_identity_conflicts_once_idx
  on public.kunthai_account_identity_conflicts (user_id, conflict_type, identity_hash);

create table if not exists public.kunthai_account_recovery_throttle (
  id bigint generated by default as identity primary key,
  request_kind text not null default 'lookup',
  request_fingerprint text not null,
  phone_hash text,
  email_hash text,
  actor_user_id uuid references auth.users(id) on delete set null,
  attempted_at timestamptz not null default now()
);

create index if not exists kunthai_account_recovery_throttle_fingerprint_idx
  on public.kunthai_account_recovery_throttle (request_fingerprint, attempted_at desc);

create index if not exists kunthai_account_recovery_throttle_phone_idx
  on public.kunthai_account_recovery_throttle (phone_hash, attempted_at desc)
  where phone_hash is not null;

create table if not exists public.kunthai_account_lookup_failures (
  id bigint generated by default as identity primary key,
  request_fingerprint text not null,
  phone_hash text,
  email_hash text,
  actor_user_id uuid references auth.users(id) on delete set null,
  failure_reason text not null check (failure_reason in ('invalid_input', 'no_match', 'rate_limited')),
  failed_at timestamptz not null default now()
);

create index if not exists kunthai_account_lookup_failures_time_idx
  on public.kunthai_account_lookup_failures (failed_at desc);

alter table public.kunthai_account_identities enable row level security;
alter table public.kunthai_account_identity_conflicts enable row level security;
alter table public.kunthai_account_recovery_throttle enable row level security;
alter table public.kunthai_account_lookup_failures enable row level security;

revoke all on table public.kunthai_account_identities from public, anon, authenticated;
revoke all on table public.kunthai_account_identity_conflicts from public, anon, authenticated;
revoke all on table public.kunthai_account_recovery_throttle from public, anon, authenticated;
revoke all on table public.kunthai_account_lookup_failures from public, anon, authenticated;

grant select, insert, update, delete on table public.kunthai_account_identities to service_role;
grant select, insert, update, delete on table public.kunthai_account_identity_conflicts to service_role;
grant select, insert, update, delete on table public.kunthai_account_recovery_throttle to service_role;
grant select, insert, update, delete on table public.kunthai_account_lookup_failures to service_role;

with source_identities as (
  select
    users.id as user_id,
    users.created_at,
    public.normalize_kunthai_email(
      coalesce(
        nullif(users.email, ''),
        nullif(users.raw_user_meta_data->>'contact_email', '')
      )
    ) as normalized_email,
    public.normalize_kunthai_phone(
      coalesce(
        nullif(users.phone, ''),
        nullif(users.raw_user_meta_data->>'phone_number', ''),
        nullif(users.raw_user_meta_data->>'phone', '')
      ),
      coalesce(
        nullif(users.raw_user_meta_data->>'country_code', ''),
        nullif(users.raw_user_meta_data->>'country', '')
      )
    ) as normalized_phone,
    coalesce(
      nullif(users.raw_user_meta_data->>'display_name', ''),
      nullif(users.raw_user_meta_data->>'full_name', ''),
      nullif(users.raw_user_meta_data->>'name', ''),
      nullif(split_part(coalesce(users.email, ''), '@', 1), ''),
      'KunThai account'
    ) as display_name
  from auth.users users
), ranked_identities as (
  select
    source.*,
    case
      when source.normalized_email is null then null
      else row_number() over (
        partition by source.normalized_email
        order by source.created_at nulls last, source.user_id
      )
    end as email_rank,
    case
      when source.normalized_phone is null then null
      else row_number() over (
        partition by source.normalized_phone
        order by source.created_at nulls last, source.user_id
      )
    end as phone_rank
  from source_identities source
)
insert into public.kunthai_account_identities (
  user_id,
  normalized_email,
  normalized_phone,
  display_name,
  created_at,
  updated_at
)
select
  ranked.user_id,
  case when ranked.email_rank = 1 then ranked.normalized_email else null end,
  case when ranked.phone_rank = 1 then ranked.normalized_phone else null end,
  ranked.display_name,
  coalesce(ranked.created_at, now()),
  now()
from ranked_identities ranked
on conflict (user_id) do update
set
  normalized_email = excluded.normalized_email,
  normalized_phone = excluded.normalized_phone,
  display_name = excluded.display_name,
  updated_at = now();

with source_identities as (
  select
    users.id as user_id,
    users.created_at,
    public.normalize_kunthai_email(
      coalesce(nullif(users.email, ''), nullif(users.raw_user_meta_data->>'contact_email', ''))
    ) as normalized_email,
    public.normalize_kunthai_phone(
      coalesce(
        nullif(users.phone, ''),
        nullif(users.raw_user_meta_data->>'phone_number', ''),
        nullif(users.raw_user_meta_data->>'phone', '')
      ),
      coalesce(
        nullif(users.raw_user_meta_data->>'country_code', ''),
        nullif(users.raw_user_meta_data->>'country', '')
      )
    ) as normalized_phone
  from auth.users users
), ranked_identities as (
  select
    source.*,
    case when source.normalized_email is null then null else row_number() over (
      partition by source.normalized_email order by source.created_at nulls last, source.user_id
    ) end as email_rank,
    case when source.normalized_phone is null then null else row_number() over (
      partition by source.normalized_phone order by source.created_at nulls last, source.user_id
    ) end as phone_rank
  from source_identities source
), conflicts as (
  select user_id, 'email'::text as conflict_type, normalized_email as identity_value
  from ranked_identities
  where email_rank > 1
  union all
  select user_id, 'phone'::text as conflict_type, normalized_phone as identity_value
  from ranked_identities
  where phone_rank > 1
)
insert into public.kunthai_account_identity_conflicts (user_id, conflict_type, identity_hash)
select
  conflicts.user_id,
  conflicts.conflict_type,
  public.kunthai_hash_identity(conflicts.identity_value)
from conflicts
on conflict (user_id, conflict_type, identity_hash) do nothing;

create or replace function public.sync_kunthai_account_identity_from_auth()
returns trigger
language plpgsql
security definer
set search_path = public, auth, pg_catalog
as $$
declare
  next_email text;
  next_phone text;
  next_display_name text;
begin
  next_email := public.normalize_kunthai_email(
    coalesce(
      nullif(new.email, ''),
      nullif(new.raw_user_meta_data->>'contact_email', '')
    )
  );
  next_phone := public.normalize_kunthai_phone(
    coalesce(
      nullif(new.phone, ''),
      nullif(new.raw_user_meta_data->>'phone_number', ''),
      nullif(new.raw_user_meta_data->>'phone', '')
    ),
    coalesce(
      nullif(new.raw_user_meta_data->>'country_code', ''),
      nullif(new.raw_user_meta_data->>'country', '')
    )
  );
  next_display_name := coalesce(
    nullif(new.raw_user_meta_data->>'display_name', ''),
    nullif(new.raw_user_meta_data->>'full_name', ''),
    nullif(new.raw_user_meta_data->>'name', ''),
    nullif(split_part(coalesce(new.email, ''), '@', 1), ''),
    'KunThai account'
  );

  insert into public.kunthai_account_identities (
    user_id,
    normalized_email,
    normalized_phone,
    display_name,
    created_at,
    updated_at
  )
  values (
    new.id,
    next_email,
    next_phone,
    next_display_name,
    coalesce(new.created_at, now()),
    now()
  )
  on conflict (user_id) do update
  set
    normalized_email = excluded.normalized_email,
    normalized_phone = excluded.normalized_phone,
    display_name = excluded.display_name,
    updated_at = now();

  return new;
exception
  when unique_violation then
    raise exception using
      errcode = '23505',
      message = 'This email or phone number is already linked to another KunThai account.';
end;
$$;

drop trigger if exists sync_kunthai_account_identity_on_auth_user on auth.users;
create trigger sync_kunthai_account_identity_on_auth_user
after insert or update of email, phone, raw_user_meta_data
on auth.users
for each row
execute function public.sync_kunthai_account_identity_from_auth();

create or replace function public.preflight_kunthai_signup(
  input_email text,
  input_phone text,
  input_country text
)
returns table (
  allowed boolean,
  conflict_code text
)
language plpgsql
security definer
set search_path = public, auth, pg_catalog
as $$
declare
  requested_email text := public.normalize_kunthai_email(input_email);
  requested_phone text := public.normalize_kunthai_phone(input_phone, input_country);
  current_user_id uuid := auth.uid();
  phone_taken boolean := false;
  email_taken boolean := false;
begin
  if requested_email is null and requested_phone is null then
    return query select false, 'invalid_identity'::text;
    return;
  end if;

  if input_phone is not null and requested_phone is null then
    return query select false, 'invalid_identity'::text;
    return;
  end if;

  if requested_phone is not null then
    select exists (
      select 1
      from public.kunthai_account_identities identity_record
      where identity_record.normalized_phone = requested_phone
        and (current_user_id is null or identity_record.user_id <> current_user_id)
    ) into phone_taken;
  end if;

  if phone_taken then
    return query select false, 'phone_exists'::text;
    return;
  end if;

  if requested_email is not null then
    select exists (
      select 1
      from public.kunthai_account_identities identity_record
      where identity_record.normalized_email = requested_email
        and (current_user_id is null or identity_record.user_id <> current_user_id)
    ) into email_taken;
  end if;

  if email_taken then
    return query select false, 'identity_unavailable'::text;
    return;
  end if;

  return query select true, null::text;
end;
$$;

create or replace function public.kunthai_request_fingerprint()
returns text
language plpgsql
stable
security definer
set search_path = public, auth, pg_catalog
as $$
declare
  headers jsonb := '{}'::jsonb;
  headers_setting text := current_setting('request.headers', true);
  network_value text;
begin
  if nullif(headers_setting, '') is not null then
    begin
      headers := headers_setting::jsonb;
    exception
      when others then
        headers := '{}'::jsonb;
    end;
  end if;

  network_value := coalesce(
    nullif(headers->>'cf-connecting-ip', ''),
    nullif(split_part(coalesce(headers->>'x-forwarded-for', ''), ',', 1), ''),
    nullif(headers->>'x-real-ip', ''),
    auth.uid()::text,
    nullif(headers->>'user-agent', ''),
    'anonymous'
  );

  return public.kunthai_hash_identity(network_value);
end;
$$;

create or replace function public.kunthai_mask_token(input_value text)
returns text
language sql
immutable
set search_path = pg_catalog
as $$
  select case
    when btrim(coalesce(input_value, '')) = '' then 'K' || repeat(chr(8226), 3)
    else left(btrim(input_value), 1) || repeat(
      chr(8226),
      least(3, greatest(2, length(btrim(input_value)) - 1))
    )
  end;
$$;

create or replace function public.kunthai_mask_name(input_name text)
returns text
language plpgsql
immutable
set search_path = public, pg_catalog
as $$
declare
  name_parts text[] := regexp_split_to_array(btrim(coalesce(input_name, '')), '\s+');
  part_count integer := coalesce(array_length(name_parts, 1), 0);
begin
  if part_count = 0 then
    return public.kunthai_mask_token('KunThai');
  end if;

  if part_count = 1 then
    return public.kunthai_mask_token(name_parts[1]);
  end if;

  return public.kunthai_mask_token(name_parts[1]) || ' ' || public.kunthai_mask_token(name_parts[part_count]);
end;
$$;

create or replace function public.kunthai_mask_email(input_email text)
returns text
language plpgsql
immutable
set search_path = pg_catalog
as $$
declare
  normalized text := lower(btrim(coalesce(input_email, '')));
  local_part text;
  domain_part text;
begin
  local_part := split_part(normalized, '@', 1);
  domain_part := split_part(normalized, '@', 2);

  if local_part = '' then
    return repeat(chr(8226), 5);
  end if;

  if domain_part = '' then
    return left(local_part, 1) || repeat(chr(8226), 4);
  end if;

  return left(local_part, 1) || repeat(chr(8226), 4) || '@' || domain_part;
end;
$$;

create or replace function public.kunthai_mask_phone(input_phone text)
returns text
language sql
immutable
set search_path = pg_catalog
as $$
  select case
    when btrim(coalesce(input_phone, '')) = '' then repeat(chr(8226), 8)
    else left(btrim(input_phone), 4) || ' ' || repeat(chr(8226), 3) || ' ' || repeat(chr(8226), 2) || right(btrim(input_phone), 3)
  end;
$$;

create or replace function public.find_kunthai_account(
  input_email text,
  input_phone text,
  input_country text
)
returns table (
  account_found boolean,
  masked_name text,
  masked_email text,
  masked_phone text,
  rate_limited boolean
)
language plpgsql
security definer
set search_path = public, auth, pg_catalog
as $$
declare
  requested_email text := public.normalize_kunthai_email(input_email);
  requested_phone text := public.normalize_kunthai_phone(input_phone, input_country);
  request_fingerprint_value text := public.kunthai_request_fingerprint();
  requested_email_hash text := public.kunthai_hash_identity(requested_email);
  requested_phone_hash text := public.kunthai_hash_identity(requested_phone);
  fingerprint_attempts integer := 0;
  phone_attempts integer := 0;
  matched_identity public.kunthai_account_identities%rowtype;
begin
  delete from public.kunthai_account_recovery_throttle
  where attempted_at < now() - interval '24 hours';

  select count(*) into fingerprint_attempts
  from public.kunthai_account_recovery_throttle attempts
  where attempts.request_fingerprint = request_fingerprint_value
    and attempts.attempted_at >= now() - interval '15 minutes';

  if requested_phone is not null then
    select count(*) into phone_attempts
    from public.kunthai_account_recovery_throttle attempts
    where attempts.phone_hash = requested_phone_hash
      and attempts.attempted_at >= now() - interval '15 minutes';
  end if;

  if fingerprint_attempts >= 20 or phone_attempts >= 5 then
    insert into public.kunthai_account_lookup_failures (
      request_fingerprint,
      phone_hash,
      email_hash,
      actor_user_id,
      failure_reason
    ) values (
      request_fingerprint_value,
      requested_phone_hash,
      requested_email_hash,
      auth.uid(),
      'rate_limited'
    );

    return query select false, null::text, null::text, null::text, true;
    return;
  end if;

  insert into public.kunthai_account_recovery_throttle (
    request_kind,
    request_fingerprint,
    phone_hash,
    email_hash,
    actor_user_id
  ) values (
    'lookup',
    request_fingerprint_value,
    requested_phone_hash,
    requested_email_hash,
    auth.uid()
  );

  if requested_email is null or requested_phone is null then
    insert into public.kunthai_account_lookup_failures (
      request_fingerprint,
      phone_hash,
      email_hash,
      actor_user_id,
      failure_reason
    ) values (
      request_fingerprint_value,
      requested_phone_hash,
      requested_email_hash,
      auth.uid(),
      'invalid_input'
    );

    return query select false, null::text, null::text, null::text, false;
    return;
  end if;

  select identity_record.*
  into matched_identity
  from public.kunthai_account_identities identity_record
  where identity_record.normalized_email = requested_email
    and identity_record.normalized_phone = requested_phone
  limit 1;

  if matched_identity.user_id is null then
    insert into public.kunthai_account_lookup_failures (
      request_fingerprint,
      phone_hash,
      email_hash,
      actor_user_id,
      failure_reason
    ) values (
      request_fingerprint_value,
      requested_phone_hash,
      requested_email_hash,
      auth.uid(),
      'no_match'
    );

    return query select false, null::text, null::text, null::text, false;
    return;
  end if;

  return query select
    true,
    public.kunthai_mask_name(matched_identity.display_name),
    public.kunthai_mask_email(matched_identity.normalized_email),
    public.kunthai_mask_phone(matched_identity.normalized_phone),
    false;
end;
$$;

revoke all on function public.normalize_kunthai_email(text) from public;
revoke all on function public.normalize_kunthai_phone(text, text) from public;
revoke all on function public.kunthai_hash_identity(text) from public;
revoke all on function public.sync_kunthai_account_identity_from_auth() from public;
revoke all on function public.kunthai_request_fingerprint() from public;
revoke all on function public.kunthai_mask_token(text) from public;
revoke all on function public.kunthai_mask_name(text) from public;
revoke all on function public.kunthai_mask_email(text) from public;
revoke all on function public.kunthai_mask_phone(text) from public;
revoke all on function public.preflight_kunthai_signup(text, text, text) from public;
revoke all on function public.find_kunthai_account(text, text, text) from public;

grant execute on function public.preflight_kunthai_signup(text, text, text) to anon, authenticated;
grant execute on function public.find_kunthai_account(text, text, text) to anon, authenticated;

grant usage, select on all sequences in schema public to service_role;

comment on table public.kunthai_account_identities is
  'Private canonical normalized email and phone registry for KunThai accounts.';
comment on table public.kunthai_account_lookup_failures is
  'Backend-only hashed audit records for failed secure account lookup attempts.';
