import Foundation
import Capacitor
import AuthenticationServices

// Native "Sign in with Apple" sheet for the KunThai iOS app.
//
// Kept inside the App target (not an npm plugin) because the community plugin
// only supports Capacitor 7, and files here are never regenerated by
// `npx cap sync ios`. JS side: src/Backend/services/appleNativeSignIn.js.
//
// Returns Apple's identity token for supabase.auth.signInWithIdToken. The
// token is only handed to the web layer of this app; nothing is logged.
@objc(KunThaiAppleSignInPlugin)
public class KunThaiAppleSignInPlugin: CAPPlugin, CAPBridgedPlugin {
    public let identifier = "KunThaiAppleSignInPlugin"
    public let jsName = "KunThaiAppleSignIn"
    public let pluginMethods: [CAPPluginMethod] = [
        CAPPluginMethod(name: "authorize", returnType: CAPPluginReturnPromise)
    ]

    // One sign-in at a time; a second tap while the sheet is up is rejected.
    private var pendingCall: CAPPluginCall?
    private var controller: ASAuthorizationController?

    @objc func authorize(_ call: CAPPluginCall) {
        guard let hashedNonce = call.getString("nonce"), !hashedNonce.isEmpty else {
            call.reject("A nonce is required.", "missing_nonce")
            return
        }

        DispatchQueue.main.async {
            if self.pendingCall != nil {
                call.reject("Sign in with Apple is already in progress.", "in_progress")
                return
            }

            let request = ASAuthorizationAppleIDProvider().createRequest()
            request.requestedScopes = [.fullName, .email]
            request.nonce = hashedNonce

            let controller = ASAuthorizationController(authorizationRequests: [request])
            controller.delegate = self
            controller.presentationContextProvider = self
            self.pendingCall = call
            self.controller = controller
            controller.performRequests()
        }
    }

    private func finish(_ body: (CAPPluginCall) -> Void) {
        guard let call = pendingCall else { return }
        pendingCall = nil
        controller = nil
        body(call)
    }
}

extension KunThaiAppleSignInPlugin: ASAuthorizationControllerDelegate {
    public func authorizationController(controller: ASAuthorizationController, didCompleteWithAuthorization authorization: ASAuthorization) {
        guard
            let credential = authorization.credential as? ASAuthorizationAppleIDCredential,
            let tokenData = credential.identityToken,
            let identityToken = String(data: tokenData, encoding: .utf8)
        else {
            finish { $0.reject("Apple did not return an identity token.", "no_token") }
            return
        }

        // One-time code (valid ~5 minutes). Only used when deleting an account,
        // where the server exchanges it to revoke Apple's tokens.
        let authorizationCode = credential.authorizationCode.flatMap { String(data: $0, encoding: .utf8) } ?? ""

        // Apple shares the name and email only on the very first authorization.
        finish { call in
            call.resolve([
                "identityToken": identityToken,
                "authorizationCode": authorizationCode,
                "givenName": credential.fullName?.givenName ?? "",
                "familyName": credential.fullName?.familyName ?? "",
                "email": credential.email ?? ""
            ])
        }
    }

    public func authorizationController(controller: ASAuthorizationController, didCompleteWithError error: Error) {
        // Only .canceled means the person closed the sheet. Other codes (e.g.
        // .unknown when no Apple ID is signed in or the entitlement is
        // missing) are real failures and must be shown, not swallowed.
        let cancelled = (error as? ASAuthorizationError)?.code == .canceled
        finish { call in
            call.reject(error.localizedDescription, cancelled ? "cancelled" : "failed")
        }
    }
}

extension KunThaiAppleSignInPlugin: ASAuthorizationControllerPresentationContextProviding {
    public func presentationAnchor(for controller: ASAuthorizationController) -> ASPresentationAnchor {
        return bridge?.viewController?.view.window ?? ASPresentationAnchor()
    }
}
